<?php
require_once __DIR__ . '/bootstrap.php';
$lid = 980000000 + (int) getmypid();
try {
	tutorpress_pmpro_lds_require_local_site();
	$ord = array(); foreach ( get_included_files() as $f ) { if ( false !== strpos( $f, 'class-pmpro-level-deletion-guard.php' ) ) { $ord[] = 0; } if ( false !== strpos( $f, 'class-pmpro-level-deletion-coordinator.php' ) ) { $ord[] = 1; } }
	tutorpress_pmpro_lds_assert( isset( $ord[0], $ord[1] ) && 0 === $ord[0] && 1 === $ord[1], 'load-order' );
	$src = file_get_contents( dirname( __DIR__, 2 ) . '/includes/utilities/class-pmpro-level-deletion-coordinator.php' ); tutorpress_pmpro_lds_assert( false !== strpos( $src, "function_exists( 'pmpro_get_membership_level_relationship_tables' )" ) && false !== strpos( $src, "function_exists( 'pmpro_delete_membership_level_relationships' )" ) && false !== strpos( $src, 'GET_LOCK( %s, 0 )' ) && false !== strpos( $src, 'RELEASE_LOCK( %s )' ) && false !== strpos( $src, 'START TRANSACTION' ) && false !== strpos( $src, 'SAVEPOINT tp_pmpro_delete_sentinel' ) && false === strpos( $src, 'class-pmpro-level-cleanup.php' ), 'api-before-lock' );
	$c = '\\TUTORPRESS_PMPRO\\PMPro_Level_Deletion_Coordinator'; $e = $lid + 1; $a = $lid + 2; $b = $lid + 3; global $wpdb; tutorpress_pmpro_lds_assert( 'missing' === $c::preflight( $lid, $a, 'courses' ) && 'ineligible' === $c::preflight( 0, $a, 'courses' ), 'missing' );
	$wpdb->insert( $wpdb->pmpro_membership_levels, array( 'id' => $e, 'name' => 'tp5-' . $e, 'description' => '', 'confirmation' => '', 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => '', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'allow_signups' => 0 ) ); tutorpress_pmpro_lds_assert( 'ineligible' === $c::preflight( $e, $a, 'courses' ), 'ineligible' );
	$wpdb->insert( $wpdb->pmpro_memberships_users, array( 'user_id' => 0, 'membership_id' => $e, 'status' => 'active', 'code_id' => 0, 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => 'Month', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'startdate' => '2000-01-01 00:00:00' ) ); tutorpress_pmpro_lds_assert( 'protected' === $c::preflight( $e, $a, 'courses' ), 'protected' );
	$wpdb->delete( $wpdb->pmpro_memberships_users, array( 'membership_id' => $e ) ); $lm = $wpdb->pmpro_membership_levelmeta; foreach ( array( array( 'tutorpress_managed', '1' ), array( 'tutorpress_course_id', (string) $b ) ) as $m ) { $wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $e, 'meta_key' => $m[0], 'meta_value' => $m[1] ) ); } update_post_meta( $a, '_tutorpress_pmpro_levels', array( $e ) ); tutorpress_pmpro_lds_assert( 'ownership_conflict' === $c::preflight( $e, $a, 'courses' ), 'own-conflict' );
	$wpdb->query( $wpdb->prepare( "DELETE FROM {$lm} WHERE pmpro_membership_level_id = %d", $e ) ); delete_post_meta( $a, '_tutorpress_pmpro_levels' ); $wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $e, 'meta_key' => 'tutorpress_course_id', 'meta_value' => (string) $a ) ); $wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $b ) ); tutorpress_pmpro_lds_assert( 'shared_unlink' === $c::preflight( $e, $a, 'courses' ), 'shared' );
	$my = $wpdb->prefix . 'tp_lds_myisam_' . $lid; $wpdb->query( 'DROP TABLE IF EXISTS `' . str_replace( '`', '', $my ) . '`' ); $wpdb->query( 'CREATE TABLE `' . str_replace( '`', '', $my ) . '` (id INT) ENGINE=MyISAM' ); $GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_membership_levels_groups'] = $wpdb->pmpro_membership_levels_groups; $wpdb->pmpro_membership_levels_groups = $my; tutorpress_pmpro_lds_assert( 'shared_unlink' === $c::preflight( $e, $a, 'courses' ), 'shared-non' ); $wpdb->pmpro_membership_levels_groups = $GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_membership_levels_groups'];
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $e, 'meta_key' => 'tutorpress_managed', 'meta_value' => '1' ) ); $wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e ) ); $wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $a ) ); tutorpress_pmpro_lds_assert( 'allowed' === $c::preflight( $e, $a, 'courses' ), 'allowed' );
	$rel = array(); foreach ( pmpro_get_membership_level_relationship_tables() as $r ) { $rel[] = $r['table']; } $full = $c::participating_write_tables( 'full' ); $sh = $c::participating_write_tables( 'shared' ); $st = $c::participating_write_tables( 'stale' );
	tutorpress_pmpro_lds_assert( empty( array_diff( $rel, $full ) ) && in_array( $wpdb->pmpro_membership_levels, $full, true ) && in_array( $wpdb->postmeta, $full, true ) && in_array( $wpdb->pmpro_groups, $full, true ) && 8 === count( $full ) && $sh === $st && array( $wpdb->pmpro_memberships_pages, $wpdb->pmpro_membership_levels_groups, $wpdb->pmpro_membership_levelmeta, $wpdb->postmeta ) === $sh && array() === $c::participating_write_tables( 'invalid' ), 'table-sets' );
	tutorpress_pmpro_lds_assert( 'ok' === $c::probe_write_tables( $full ) && false === $c::session_in_transaction() && 'error' === $c::probe_write_tables( array() ) && 'error' === $c::probe_write_tables( array( '' ) ), 'probe-idle' );
	tutorpress_pmpro_lds_assert( 'nontransactional' === $c::probe_write_tables( array( $my ) ), 'known-non' );
	$GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_groups'] = $wpdb->pmpro_groups; $wpdb->pmpro_groups = $my; tutorpress_pmpro_lds_assert( 'nontransactional' === $c::preflight( $e, $a, 'courses' ), 'pre-non' );
	$wpdb->pmpro_groups = 'tp_lds_no_table'; tutorpress_pmpro_lds_assert( 'error' === $c::probe_write_tables( array( 'tp_lds_no_table' ) ) && 'infrastructure' === $c::preflight( $e, $a, 'courses' ), 'probe-err' ); $wpdb->pmpro_groups = $GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_groups'];
	$wpdb->query( 'START TRANSACTION' ); tutorpress_pmpro_lds_assert( true === $c::session_in_transaction() && 'outer_transaction_active' === $c::preflight( $e, $a, 'courses' ), 'outer-active' ); $wpdb->query( 'ROLLBACK' );
	$GLOBALS['tutorpress_pmpro_lds_in_txn'] = null; tutorpress_pmpro_lds_assert( null === $c::session_in_transaction() && 'transaction_state_unknown' === $c::preflight( $e, $a, 'courses' ), 'outer-unk' ); unset( $GLOBALS['tutorpress_pmpro_lds_in_txn'] );
	$n = $c::advisory_lock_name( $e ); $h = substr( md5( (string) $wpdb->dbname . (string) $wpdb->prefix ), 0, 12 ); tutorpress_pmpro_lds_assert( 'tp_pmpro_delete:' . $h . ':' . $e === $n && strlen( $n ) <= 64, 'lock-name' );
	$wpdb->last_error = ''; $GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $n; tutorpress_pmpro_lds_assert( 'acquired' === $c::acquire_advisory_lock( $e ) && 'released' === $c::release_advisory_lock( $e ), 'lock-rw' );
	$GLOBALS['tutorpress_pmpro_lds_lock'] = '0'; tutorpress_pmpro_lds_assert( 'busy' === $c::acquire_advisory_lock( $e ), 'lock-busy' );
	$GLOBALS['tutorpress_pmpro_lds_lock'] = null; $wpdb->last_error = 'FUNCTION GET_LOCK does not exist'; tutorpress_pmpro_lds_assert( 'lock_unsupported' === $c::acquire_advisory_lock( $e ), 'lock-unsup' );
	$wpdb->last_error = 'permission denied'; tutorpress_pmpro_lds_assert( 'lock_error' === $c::acquire_advisory_lock( $e ) && 'lock_error' === $c::acquire_advisory_lock( 0 ), 'lock-err' ); unset( $GLOBALS['tutorpress_pmpro_lds_lock'] );
	$GLOBALS['tutorpress_pmpro_lds_unlock'] = '0'; tutorpress_pmpro_lds_assert( 'lock_release_failed' === $c::release_advisory_lock( $e ), 'lock-rel-fail' ); unset( $GLOBALS['tutorpress_pmpro_lds_unlock'] );
	tutorpress_pmpro_lds_assert( 'ok' === $c::control_transaction( 'begin' ) && true === $c::session_in_transaction() && 'ok' === $c::control_transaction( 'savepoint' ) && 'ok' === $c::control_transaction( 'rollback' ) && false === $c::session_in_transaction(), 'txn-begin' );
	$GLOBALS['tutorpress_pmpro_lds_in_txn'] = true; tutorpress_pmpro_lds_assert( 'outer_transaction_active' === $c::control_transaction( 'begin' ), 'txn-outer' ); $GLOBALS['tutorpress_pmpro_lds_in_txn'] = null; tutorpress_pmpro_lds_assert( 'transaction_state_unknown' === $c::control_transaction( 'begin' ), 'txn-unk' ); unset( $GLOBALS['tutorpress_pmpro_lds_in_txn'] ); tutorpress_pmpro_lds_assert( false === $c::session_in_transaction(), 'txn-no-sql' );
	$GLOBALS['tutorpress_pmpro_lds_txn'] = false; tutorpress_pmpro_lds_assert( 'begin_failed' === $c::control_transaction( 'begin' ) && 'rollback_failed' === $c::control_transaction( 'rollback' ) && 'transaction_outcome_unknown' === $c::control_transaction( 'commit' ), 'txn-seams' );
	unset( $GLOBALS['tutorpress_pmpro_lds_txn'] ); tutorpress_pmpro_lds_assert( 'ok' === $c::control_transaction( 'begin' ), 'txn-b2' ); $GLOBALS['tutorpress_pmpro_lds_txn'] = false; tutorpress_pmpro_lds_assert( 'commit_failed' === $c::control_transaction( 'commit' ) && false === $c::session_in_transaction() && 'hook_transaction_invalidated' === $c::control_transaction( 'release_sp' ), 'txn-cf-sent' ); unset( $GLOBALS['tutorpress_pmpro_lds_txn'] );
	$GLOBALS['tutorpress_pmpro_lds_cache_false'] = 1; tutorpress_pmpro_lds_assert( 'ok' === $c::invalidate_deletion_caches( $e, array( $a ) ), 'cache-false' ); unset( $GLOBALS['tutorpress_pmpro_lds_cache_false'] );
	$c::arm_shutdown_guard( $e, array( $a ) ); $c::disarm_shutdown_guard(); $c::run_shutdown_guard(); $c::arm_shutdown_guard( $e, array( $a ) ); tutorpress_pmpro_lds_assert( 'ok' === $c::control_transaction( 'begin' ), 'sd-b' ); $c::run_shutdown_guard(); tutorpress_pmpro_lds_assert( false === $c::session_in_transaction(), 'shutdown' );
	require_once dirname( __DIR__, 2 ) . '/includes/utilities/class-pmpro-level-cleanup.php';
	$has = false; foreach ( (array) ( isset( $GLOBALS['wp_filter']['pmpro_delete_membership_level'] ) ? ( $GLOBALS['wp_filter']['pmpro_delete_membership_level']->callbacks[10] ?? array() ) : array() ) as $cb ) { $has = $has || ( is_array( $cb['function'] ) && 'cleanup_deleted_pmpro_level_meta' === ( $cb['function'][1] ?? '' ) ); } tutorpress_pmpro_lds_assert( $has, 'has-init-listener' ); tutorpress_pmpro_lds_assert( false !== strpos( file_get_contents( dirname( __DIR__, 2 ) . '/includes/init.php' ), 'if ( $skip ) { return; }' ), 'shut-skip' );
	$hn = 0; $hf = function() use ( &$hn ) { $hn++; }; add_action( 'pmpro_delete_membership_level', $hf ); add_action( 'tutorpress_pmpro_membership_level_deleted', $hf ); tutorpress_pmpro_lds_assert( 'missing' === $c::delete_level( $lid, $a, 'courses' ) && 0 === $hn, 'skip-no-hook' ); remove_action( 'pmpro_delete_membership_level', $hf ); remove_action( 'tutorpress_pmpro_membership_level_deleted', $hf );
	tutorpress_pmpro_lds_assert( $a === (int) wp_insert_post( array( 'import_id' => $a, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'tp9a-' . $a ) ), 'post9a' ); $GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $a; update_post_meta( $a, '_tutorpress_pmpro_levels', array( $e ) ); if ( true === $c::session_in_transaction() ) { $wpdb->query( 'COMMIT' ); }
	$hn = 0; $hf = function() use ( &$hn ) { $hn++; }; add_action( 'pmpro_delete_membership_level', $hf ); add_action( 'tutorpress_pmpro_membership_level_deleted', $hf ); $GLOBALS['tutorpress_pmpro_lds_lock'] = '0'; tutorpress_pmpro_lds_assert( 'busy' === $c::delete_level( $e, $a, 'courses' ) && 0 === $hn, 'dl-busy' ); unset( $GLOBALS['tutorpress_pmpro_lds_lock'] );
	$GLOBALS['tutorpress_pmpro_lds_txn'] = false; tutorpress_pmpro_lds_assert( 'begin_failed' === $c::delete_level( $e, $a, 'courses' ) && 0 === $hn, 'dl-begin' ); unset( $GLOBALS['tutorpress_pmpro_lds_txn'] );
	$wpdb->insert( $wpdb->pmpro_memberships_users, array( 'user_id' => 0, 'membership_id' => $e, 'status' => 'active', 'code_id' => 0, 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => 'Month', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'startdate' => '2000-01-01 00:00:00' ) ); tutorpress_pmpro_lds_assert( 'protected' === $c::delete_level( $e, $a, 'courses' ) && 0 === $hn, 'dl-prot' ); $wpdb->delete( $wpdb->pmpro_memberships_users, array( 'membership_id' => $e ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $b ) ); tutorpress_pmpro_lds_assert( 'ok' === $c::delete_level( $e, $a, 'courses' ) && 0 === $hn && $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $e ) ), 'dl-shared' ); $wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e ) ); $wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $a ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$lm} WHERE pmpro_membership_level_id = %d", $e ) ); foreach ( array( array( 'tutorpress_managed', '1' ), array( 'tutorpress_course_id', (string) $a ) ) as $m ) { $wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $e, 'meta_key' => $m[0], 'meta_value' => $m[1] ) ); } update_post_meta( $a, '_tutorpress_pmpro_levels', array( $e ) );
	$sf = function() { $GLOBALS['tutorpress_pmpro_lds_in_txn'] = false; }; add_action( 'pmpro_delete_membership_level', $sf ); tutorpress_pmpro_lds_assert( 'hook_transaction_invalidated' === $c::delete_level( $e, $a, 'courses' ) && $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $e ) ), 'dl-sent' ); remove_action( 'pmpro_delete_membership_level', $sf ); unset( $GLOBALS['tutorpress_pmpro_lds_in_txn'] ); $wpdb->query( 'ROLLBACK' );
	$qf = function( $sql ) use ( $wpdb ) { if ( false !== strpos( $sql, (string) $wpdb->pmpro_membership_levels ) && 0 === stripos( ltrim( $sql ), 'DELETE' ) ) { $GLOBALS['tutorpress_pmpro_lds_txn'] = false; } return $sql; }; add_filter( 'query', $qf ); tutorpress_pmpro_lds_assert( 'commit_failed' === $c::delete_level( $e, $a, 'courses' ) && $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $e ) ), 'dl-cf' ); remove_filter( 'query', $qf ); unset( $GLOBALS['tutorpress_pmpro_lds_txn'] );
	remove_action( 'pmpro_delete_membership_level', $hf ); remove_action( 'tutorpress_pmpro_membership_level_deleted', $hf );
	$lsu = null; $lsr = true; add_action( 'pmpro_delete_membership_level', function() use ( $c, &$lsu, $a, $e ) { $lsu = $c::deletion_listener_suppressed() && in_array( $e, (array) get_post_meta( $a, '_tutorpress_pmpro_levels', true ), true ); }, 11 ); add_action( 'tutorpress_pmpro_membership_level_deleted', function() use ( $c, &$lsr ) { $lsr = $c::deletion_listener_suppressed(); } );
	$ord = array(); add_action( 'pmpro_delete_membership_level', function( $id ) use ( &$ord, $wpdb ) { $ord[] = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $id ) ) ? 'h' : 'x'; }, 1 ); add_action( 'tutorpress_pmpro_membership_level_deleted', function() use ( &$ord, $wpdb, $e ) { $ord[] = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $e ) ) ? 'y' : 'p'; } ); $GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $c::advisory_lock_name( $e ); $GLOBALS['tutorpress_pmpro_lds_rel_calls'] = 0;
	tutorpress_pmpro_lds_assert( 'ok' === $c::delete_level( $e, $a, 'courses' ) && array( 'h', 'p' ) === $ord && null === $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $e ) ) && '' === get_post_meta( $a, '_tutorpress_pmpro_levels', true ) && 1 === $GLOBALS['tutorpress_pmpro_lds_rel_calls'] && false === $c::session_in_transaction(), 'full-ok' );
	tutorpress_pmpro_lds_assert( true === $lsu && false === $lsr, 'dl-listen' );
	$mk = function( $id ) use ( $wpdb, $lm, $a, $c ) { $wpdb->insert( $wpdb->pmpro_membership_levels, array( 'id' => $id, 'name' => 'tp9b-' . $id, 'description' => '', 'confirmation' => '', 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => '', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'allow_signups' => 0 ) ); foreach ( array( array( 'tutorpress_managed', '1' ), array( 'tutorpress_course_id', (string) $a ) ) as $m ) { $wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $id, 'meta_key' => $m[0], 'meta_value' => $m[1] ) ); } $wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $id, 'page_id' => $a ) ); update_post_meta( $a, '_tutorpress_pmpro_levels', array( $id ) ); if ( true === $c::session_in_transaction() ) { $wpdb->query( 'COMMIT' ); } $GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $c::advisory_lock_name( $id ); };
	$f = $lid + 4; $mk( $f ); $GLOBALS['tutorpress_pmpro_lds_unlock'] = '0'; $pn = 0; add_action( 'tutorpress_pmpro_membership_level_deleted', function() use ( &$pn ) { $pn++; } ); tutorpress_pmpro_lds_assert( 'committed_with_warning' === $c::delete_level( $f, $a, 'courses' ) && 0 === $pn && ! $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $f ) ), 'dl-relwarn' ); unset( $GLOBALS['tutorpress_pmpro_lds_unlock'] );
	$g = $lid + 5; $mk( $g ); add_action( 'tutorpress_pmpro_membership_level_deleted', function() { throw new RuntimeException( 'x' ); } ); tutorpress_pmpro_lds_assert( 'ok' === $c::delete_level( $g, $a, 'courses' ), 'dl-hookthrow' );
	$h = $lid + 6; $mk( $h ); do_action( 'pmpro_delete_membership_level', $h ); tutorpress_pmpro_lds_assert( 'free' === get_post_meta( $a, '_tutor_course_price_type', true ) && '' === get_post_meta( $a, '_tutorpress_pmpro_levels', true ) && false === $c::deletion_listener_suppressed(), 'dl-admin' );
	$GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_membership_levels'] = $wpdb->pmpro_membership_levels; $wpdb->pmpro_membership_levels = 'tp_lds_missing'; tutorpress_pmpro_lds_assert( 'infrastructure' === $c::preflight( $e, $a, 'courses' ), 'infra' ); tutorpress_pmpro_lds_pass( 'preflight contract' );
} catch ( Throwable $e ) { exit( 1 ); } finally { global $wpdb; $c = '\\TUTORPRESS_PMPRO\\PMPro_Level_Deletion_Coordinator'; $c::disarm_shutdown_guard(); $c::restore_deletion_listener(); $wpdb->query( 'ROLLBACK' ); unset( $GLOBALS['tutorpress_pmpro_lds_lock'], $GLOBALS['tutorpress_pmpro_lds_unlock'], $GLOBALS['tutorpress_pmpro_lds_in_txn'], $GLOBALS['tutorpress_pmpro_lds_txn'], $GLOBALS['tutorpress_pmpro_lds_cache_false'] ); $wpdb->query( 'DROP TABLE IF EXISTS `' . str_replace( '`', '', $wpdb->prefix . 'tp_lds_myisam_' . $lid ) . '`' ); foreach ( $GLOBALS['tutorpress_pmpro_lds_reg']['wpdb'] as $p => $v ) { $wpdb->$p = $v; } $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid + 1 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid + 1 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levelmeta} WHERE pmpro_membership_level_id = %d", $lid + 1 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d", $lid + 1 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->postmeta} WHERE post_id IN (%d,%d) AND meta_key = %s", $lid + 2, $lid + 3, '_tutorpress_pmpro_levels' ) ); foreach ( array( $lid + 4, $lid + 5, $lid + 6 ) as $x ) { $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $x ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levelmeta} WHERE pmpro_membership_level_id = %d", $x ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d", $x ) ); } tutorpress_pmpro_lds_cleanup(); }
