<?php
require_once __DIR__ . '/bootstrap.php';
$base = 980000000 + (int) getmypid(); $held = $base + 71; $first = $base + 81; $second = $base + 91;
$posts = array(); $levels = array( $held, $first, $second ); $groups = array();
$sub = 0;
$author = 0;
$sort_cleanup = function () use ( &$posts, &$levels, &$groups ) {
	global $wpdb;
	foreach ( $posts as $id ) { $gid = (int) get_post_meta( $id, '_tutorpress_pmpro_group_id', true ); if ( $gid ) { $groups[] = $gid; } $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_pages} WHERE page_id = %d", $id ) ); $GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $id; }
	foreach ( $levels as $lid ) { $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levelmeta} WHERE pmpro_membership_level_id = %d", $lid ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d", $lid ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels_groups} WHERE level = %d", $lid ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ); }
	foreach ( $groups as $gid ) { $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels_groups} WHERE `group` = %d", $gid ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_groups} WHERE id = %d", $gid ) ); }
	tutorpress_pmpro_lds_cleanup();
};
try {
	tutorpress_pmpro_lds_require_local_site();
	require_once dirname( __DIR__, 2 ) . '/includes/rest/class-pmpro-subscriptions-controller.php';
	$merge = new ReflectionMethod( 'TutorPress_PMPro_Subscriptions_Controller', 'merge_display_order' );
	$cases = array(
		array( 'dup-slot', array( 1, 9, 1, 2 ), array( 2, 1 ), array( 2, 9, 1, 1 ) ),
		array( 'perm', array( 1, 1, 2 ), array( 2, 1, 1 ), array( 2, 1, 1 ) ), array( 'append', array( 1, 1 ), array( 1, 4, 1 ), array( 1, 1, 4 ) ),
		array( 'empty', array(), array( 2, 1, 2 ), array( 2, 1, 2 ) ), array( 'nonpositive', array( 5, 0, -1, 2 ), array( 2, 5 ), array( 2, 0, -1, 5 ) ),
	);
	foreach ( $cases as $case ) {
		tutorpress_pmpro_lds_assert( $case[3] === $merge->invoke( null, $case[1], $case[2] ), $case[0] );
	}
	tutorpress_pmpro_lds_pass( 'merge-order' );
	$ctl = new TutorPress_PMPro_Subscriptions_Controller(); $preset = array( $first, $held, $second ); $submitted = array( $second, $first ); $expect = array( $second, $held, $first );
	foreach ( array( 'courses' => $base + 1, 'course-bundle' => $base + 2 ) as $type => $oid ) {
		tutorpress_pmpro_lds_assert( $oid === (int) wp_insert_post( array( 'import_id' => $oid, 'post_type' => $type, 'post_status' => 'publish', 'post_title' => 'es2-' . $oid ) ), $type );
		$posts[] = $oid;
		update_post_meta( $oid, '_tutorpress_pmpro_levels', $preset );
		$req = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions/sort' );
		$req->set_param( 'object_id', $oid );
		$req->set_param( 'ordered_ids', $submitted );
		$res = $ctl->sort_subscription_plans( $req );
		$stored = array_map( 'intval', (array) get_post_meta( $oid, '_tutorpress_pmpro_levels', true ) );
		tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && ! empty( $res->get_data()['success'] ) && $expect === $stored && $held === (int) $stored[1], 'slot-' . $type );
	}
	tutorpress_pmpro_lds_pass( 'persist-slots' );
	$empty = $base + 3;
	tutorpress_pmpro_lds_assert( $empty === (int) wp_insert_post( array( 'import_id' => $empty, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es2e-' . $empty ) ), 'empty-post' );
	$posts[] = $empty;
	delete_post_meta( $empty, '_tutorpress_pmpro_levels' );
	$req = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions/sort' ); $req->set_param( 'object_id', $empty ); $req->set_param( 'ordered_ids', array( $second, $first ) );
	$res = $ctl->sort_subscription_plans( $req ); $stored = array_map( 'intval', (array) get_post_meta( $empty, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && array( $second, $first ) === $stored, 'empty-store' );
	tutorpress_pmpro_lds_pass( 'persist-empty' );
	wp_set_current_user( 1 );
	$course = $base + 6;
	tutorpress_pmpro_lds_assert( $course === (int) wp_insert_post( array( 'import_id' => $course, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es3-' . $course ) ), 'course-put-post' );
	$posts[] = $course;
	update_post_meta( $course, '_tutorpress_pmpro_levels', $preset );
	$req = new WP_REST_Request( 'PUT', '/tutorpress/v1/courses/' . $course . '/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $second, $first ) ) ) );
	$res = rest_do_request( $req );
	$stored = array_map( 'intval', (array) get_post_meta( $course, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && ! empty( $res->get_data()['success'] ) && $expect === $stored, 'course-put' );
	tutorpress_pmpro_lds_pass( 'course-put' );
	$contract = $base + 7;
	tutorpress_pmpro_lds_assert( $contract === (int) wp_insert_post( array( 'import_id' => $contract, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es4-' . $contract ) ), 'course-contract-post' );
	$posts[] = $contract;
	update_post_meta( $contract, '_tutorpress_pmpro_levels', $preset );
	$path = '/tutorpress/v1/courses/' . $contract . '/subscriptions/sort';
	$sub = wp_insert_user( array( 'user_login' => 'es4s-' . $base, 'user_pass' => 'x', 'role' => 'subscriber' ) );
	tutorpress_pmpro_lds_assert( ! is_wp_error( $sub ) && (int) $sub > 0 && in_array( 'subscriber', (array) get_userdata( (int) $sub )->roles, true ), 'course-sub-user' );
	wp_set_current_user( (int) $sub );
	$req = new WP_REST_Request( 'PUT', $path );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $second, $first ) ) ) );
	$res = rest_do_request( $req );
	$data = $res->get_data();
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 403 === (int) $res->get_status() && is_array( $data ) && 'rest_forbidden' === ( $data['code'] ?? '' ), 'course-forbidden' );
	tutorpress_pmpro_lds_pass( 'course-forbidden' );
	wp_set_current_user( 1 );
	$req = new WP_REST_Request( 'PUT', $path );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( '{}' );
	$res = rest_do_request( $req );
	$data = $res->get_data();
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 400 === (int) $res->get_status() && is_array( $data ) && 'rest_missing_callback_param' === ( $data['code'] ?? '' ), 'course-missing' );
	tutorpress_pmpro_lds_pass( 'course-missing' );
	$req = new WP_REST_Request( 'PUT', $path );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( 'label' => (string) $second ) ) ) );
	$res = rest_do_request( $req );
	$data = $res->get_data();
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 400 === (int) $res->get_status() && is_array( $data ) && 'rest_invalid_param' === ( $data['code'] ?? '' ), 'course-invalid' );
	tutorpress_pmpro_lds_pass( 'course-invalid' );
	$req = new WP_REST_Request( 'GET', $path );
	$res = rest_do_request( $req );
	$data = $res->get_data();
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 404 === (int) $res->get_status() && is_array( $data ) && 'rest_no_route' === ( $data['code'] ?? '' ), 'course-get-method' );
	tutorpress_pmpro_lds_pass( 'course-get-method' );
	$req = new WP_REST_Request( 'POST', $path );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( (string) $second, (string) $first ) ) ) );
	$res = rest_do_request( $req );
	$stored = array_map( 'intval', (array) get_post_meta( $contract, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && ! empty( $res->get_data()['success'] ) && $expect === $stored, 'course-post-strings' );
	tutorpress_pmpro_lds_pass( 'course-post-strings' );
	$owned = $base + 8;
	tutorpress_pmpro_lds_assert( $owned === (int) wp_insert_post( array( 'import_id' => $owned, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es4a-' . $owned, 'post_author' => 1 ) ), 'course-edit-posts-post' );
	$posts[] = $owned;
	update_post_meta( $owned, '_tutorpress_pmpro_levels', $preset );
	$author = wp_insert_user( array( 'user_login' => 'es4a-' . $base, 'user_pass' => 'x', 'role' => 'author' ) );
	tutorpress_pmpro_lds_assert( ! is_wp_error( $author ) && (int) $author > 0 && in_array( 'author', (array) get_userdata( (int) $author )->roles, true ), 'course-edit-posts-user' );
	wp_set_current_user( (int) $author );
	tutorpress_pmpro_lds_assert( current_user_can( 'edit_posts' ) && ! current_user_can( 'edit_post', $owned ), 'course-edit-posts-caps' );
	$req = new WP_REST_Request( 'PUT', '/tutorpress/v1/courses/' . $owned . '/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $second, $first ) ) ) );
	$res = rest_do_request( $req );
	$stored = array_map( 'intval', (array) get_post_meta( $owned, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && ! empty( $res->get_data()['success'] ) && $expect === $stored, 'course-edit-posts' );
	tutorpress_pmpro_lds_pass( 'course-edit-posts' );
	wp_set_current_user( 1 );
	$refresh = $base + 9;
	tutorpress_pmpro_lds_assert( $refresh === (int) wp_insert_post( array( 'import_id' => $refresh, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es4r-' . $refresh, 'post_author' => 1 ) ), 'course-refresh-post' );
	$posts[] = $refresh;
	$make = function( $name ) use ( $ctl, $refresh ) {
		$r = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions' );
		$r->set_param( 'object_id', $refresh );
		$r->set_param( 'plan_name', $name );
		$r->set_param( 'regular_price', 1 );
		$r->set_param( 'payment_type', 'one_time' );
		$res = $ctl->create_subscription_plan( $r );
		$data = $res instanceof WP_REST_Response ? $res->get_data() : array();
		return (int) ( is_array( $data ) ? ( $data['data']['id'] ?? 0 ) : 0 );
	};
	$p1 = $make( 'es4r-a' );
	$p2 = $make( 'es4r-b' );
	$p3 = $make( 'es4r-c' );
	$levels[] = $p1; $levels[] = $p2; $levels[] = $p3;
	$stored = array_map( 'intval', (array) get_post_meta( $refresh, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $p1 && $p2 && $p3 && array( $p1, $p2, $p3 ) === $stored, 'course-refresh-order' );
	$state = '\\TUTORPRESS_PMPRO\\PMPro_Level_Removal_State';
	update_post_meta( $refresh, $state::META_KEY, array( 'version' => 1, 'levels' => array( (int) $p1 => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	$state::invalidate_object( $refresh );
	$gid = (int) get_post_meta( $refresh, '_tutorpress_pmpro_group_id', true );
	if ( $gid ) { $groups[] = $gid; }
	$req = new WP_REST_Request( 'PUT', '/tutorpress/v1/courses/' . $refresh . '/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $p3, $p2 ) ) ) );
	$res = rest_do_request( $req );
	$stored = array_map( 'intval', (array) get_post_meta( $refresh, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && array( $p1, $p3, $p2 ) === $stored, 'course-refresh-meta' );
	$req = new WP_REST_Request( 'GET', '/tutorpress/v1/courses/' . $refresh . '/subscriptions' );
	$res = rest_do_request( $req );
	$body = $res->get_data();
	$ids = wp_list_pluck( (array) ( is_array( $body ) ? ( $body['data']['plans'] ?? array() ) : array() ), 'id' );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && array( (int) $p3, (int) $p2 ) === $ids, 'course-refresh' );
	tutorpress_pmpro_lds_pass( 'course-refresh' );
	$bundle = $base + 10;
	tutorpress_pmpro_lds_assert( $bundle === (int) wp_insert_post( array( 'import_id' => $bundle, 'post_type' => 'course-bundle', 'post_status' => 'publish', 'post_title' => 'es5-' . $bundle, 'post_author' => 1 ) ), 'bundle-put-post' );
	$posts[] = $bundle;
	update_post_meta( $bundle, '_tutorpress_pmpro_levels', $preset );
	global $wpdb;
	$pages_before = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE page_id = %d", $bundle ) );
	$req = new WP_REST_Request( 'PUT', '/tutorpress/v1/bundles/' . $bundle . '/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $second, $first ) ) ) );
	$res = rest_do_request( $req );
	$stored = array_map( 'intval', (array) get_post_meta( $bundle, '_tutorpress_pmpro_levels', true ) );
	$pages_after = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE page_id = %d", $bundle ) );
	tutorpress_pmpro_lds_assert( 0 === $pages_before && $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && ! empty( $res->get_data()['success'] ) && $expect === $stored && 0 === $pages_after, 'bundle-put' );
	tutorpress_pmpro_lds_pass( 'bundle-put' );
	$bundle_path = '/tutorpress/v1/bundles/' . $bundle . '/subscriptions/sort';
	wp_set_current_user( (int) $sub );
	$req = new WP_REST_Request( 'PUT', $bundle_path );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $second, $first ) ) ) );
	$res = rest_do_request( $req );
	$data = $res->get_data();
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 403 === (int) $res->get_status() && is_array( $data ) && 'rest_forbidden' === ( $data['code'] ?? '' ), 'bundle-forbidden' );
	tutorpress_pmpro_lds_pass( 'bundle-forbidden' );
	wp_set_current_user( 1 );
	$req = new WP_REST_Request( 'PUT', $bundle_path );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( '{}' );
	$res = rest_do_request( $req );
	$data = $res->get_data();
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 400 === (int) $res->get_status() && is_array( $data ) && 'rest_missing_callback_param' === ( $data['code'] ?? '' ), 'bundle-missing' );
	tutorpress_pmpro_lds_pass( 'bundle-missing' );
	$refresh_bundle = $base + 11;
	tutorpress_pmpro_lds_assert( $refresh_bundle === (int) wp_insert_post( array( 'import_id' => $refresh_bundle, 'post_type' => 'course-bundle', 'post_status' => 'publish', 'post_title' => 'es5r-' . $refresh_bundle, 'post_author' => 1 ) ), 'bundle-refresh-post' );
	$posts[] = $refresh_bundle;
	$make_bundle = function ( $name ) use ( $ctl, $refresh_bundle ) {
		$r = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions' );
		$r->set_param( 'object_id', $refresh_bundle );
		$r->set_param( 'plan_name', $name );
		$r->set_param( 'regular_price', 1 );
		$r->set_param( 'payment_type', 'one_time' );
		$res = $ctl->create_subscription_plan( $r );
		$data = $res instanceof WP_REST_Response ? $res->get_data() : array();
		return (int) ( is_array( $data ) ? ( $data['data']['id'] ?? 0 ) : 0 );
	};
	$b1 = $make_bundle( 'es5r-a' );
	$b2 = $make_bundle( 'es5r-b' );
	$levels[] = $b1;
	$levels[] = $b2;
	$gid = (int) get_post_meta( $refresh_bundle, '_tutorpress_pmpro_group_id', true );
	if ( $gid ) { $groups[] = $gid; }
	$req = new WP_REST_Request( 'PUT', '/tutorpress/v1/bundles/' . $refresh_bundle . '/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $b2, $b1 ) ) ) );
	rest_do_request( $req );
	$req = new WP_REST_Request( 'GET', '/tutorpress/v1/bundles/' . $refresh_bundle . '/subscriptions' );
	$res = rest_do_request( $req );
	$body = $res->get_data();
	$ids = wp_list_pluck( (array) ( is_array( $body ) ? ( $body['data']['plans'] ?? array() ) : array() ), 'id' );
	tutorpress_pmpro_lds_assert( $b1 && $b2 && $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && array( (int) $b2, (int) $b1 ) === $ids, 'bundle-refresh' );
	tutorpress_pmpro_lds_pass( 'bundle-refresh' );
	$invalid = $base + 12;
	tutorpress_pmpro_lds_assert( $invalid === (int) wp_insert_post( array( 'import_id' => $invalid, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es6-' . $invalid, 'post_author' => 1 ) ), 'course-invalid-state-post' );
	$posts[] = $invalid;
	update_post_meta( $invalid, '_tutorpress_pmpro_levels', $preset );
	update_post_meta( $invalid, $state::META_KEY, array( 'version' => 1, 'levels' => array( (int) $held => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	add_post_meta( $invalid, $state::META_KEY, array( 'version' => 2 ), false );
	wp_cache_delete( $invalid, 'post_meta' );
	$state::invalidate_object( $invalid );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $held, 'page_id' => $invalid ) );
	$pages_before = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $held, $invalid ) );
	$req = new WP_REST_Request( 'PUT', '/tutorpress/v1/courses/' . $invalid . '/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $second, $first ) ) ) );
	$res = rest_do_request( $req );
	$data = $res->get_data();
	$stored = array_map( 'intval', (array) get_post_meta( $invalid, '_tutorpress_pmpro_levels', true ) );
	$pages_after = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $held, $invalid ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 500 === (int) $res->get_status() && is_array( $data ) && 'invalid_state' === ( $data['code'] ?? '' ) && $preset === $stored && 1 === $pages_before && 1 === $pages_after, 'course-invalid-state' );
	tutorpress_pmpro_lds_pass( 'course-invalid-state' );
	$retired = $base + 13;
	tutorpress_pmpro_lds_assert( $retired === (int) wp_insert_post( array( 'import_id' => $retired, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es6r-' . $retired, 'post_author' => 1 ) ), 'course-retired-post' );
	$posts[] = $retired;
	$make_retired = function ( $name ) use ( $ctl, $retired ) {
		$r = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions' );
		$r->set_param( 'object_id', $retired );
		$r->set_param( 'plan_name', $name );
		$r->set_param( 'regular_price', 1 );
		$r->set_param( 'payment_type', 'one_time' );
		$res = $ctl->create_subscription_plan( $r );
		$data = $res instanceof WP_REST_Response ? $res->get_data() : array();
		return (int) ( is_array( $data ) ? ( $data['data']['id'] ?? 0 ) : 0 );
	};
	$r1 = $make_retired( 'es6r-a' );
	$r2 = $make_retired( 'es6r-b' );
	$r3 = $make_retired( 'es6r-c' );
	$levels[] = $r1; $levels[] = $r2; $levels[] = $r3;
	$stored = array_map( 'intval', (array) get_post_meta( $retired, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $r1 && $r2 && $r3 && array( $r1, $r2, $r3 ) === $stored, 'course-retired-order' );
	update_post_meta( $retired, $state::META_KEY, array( 'version' => 1, 'levels' => array( (int) $r1 => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	$state::invalidate_object( $retired );
	$gid = (int) get_post_meta( $retired, '_tutorpress_pmpro_group_id', true );
	if ( $gid ) { $groups[] = $gid; }
	$pages_before = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r1, $retired ) );
	$req = new WP_REST_Request( 'PUT', '/tutorpress/v1/courses/' . $retired . '/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'plan_order' => array( $r3, $r2 ) ) ) );
	$res = rest_do_request( $req );
	$stored = array_map( 'intval', (array) get_post_meta( $retired, '_tutorpress_pmpro_levels', true ) );
	$pages_after = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r1, $retired ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && array( $r1, $r3, $r2 ) === $stored && 1 === $pages_before && 1 === $pages_after, 'course-retired-meta' );
	$req = new WP_REST_Request( 'GET', '/tutorpress/v1/courses/' . $retired . '/subscriptions' );
	$res = rest_do_request( $req );
	$body = $res->get_data();
	$ids = wp_list_pluck( (array) ( is_array( $body ) ? ( $body['data']['plans'] ?? array() ) : array() ), 'id' );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && array( (int) $r3, (int) $r2 ) === $ids, 'course-retired-keep' );
	tutorpress_pmpro_lds_pass( 'course-retired-keep' );
	$legacy = $base + 14;
	tutorpress_pmpro_lds_assert( $legacy === (int) wp_insert_post( array( 'import_id' => $legacy, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es6l-' . $legacy, 'post_author' => 1 ) ), 'legacy-post-post' );
	$posts[] = $legacy;
	update_post_meta( $legacy, '_tutorpress_pmpro_levels', $preset );
	$req = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions/sort' );
	$req->set_header( 'Content-Type', 'application/json' );
	$req->set_body( wp_json_encode( array( 'object_id' => $legacy, 'ordered_ids' => array( $second, $first ) ) ) );
	$res = rest_do_request( $req );
	$stored = array_map( 'intval', (array) get_post_meta( $legacy, '_tutorpress_pmpro_levels', true ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && ! empty( $res->get_data()['success'] ) && $expect === $stored, 'legacy-post' );
	tutorpress_pmpro_lds_pass( 'legacy-post' );
	$same = $base + 4;
	tutorpress_pmpro_lds_assert( $same === (int) wp_insert_post( array( 'import_id' => $same, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es2u-' . $same ) ), 'same-post' );
	$posts[] = $same;
	update_post_meta( $same, '_tutorpress_pmpro_levels', array( $first, $second ) );
	$writes = 0;
	$count_fn = static function ( $check, $object_id, $meta_key ) use ( &$writes ) { if ( '_tutorpress_pmpro_levels' === $meta_key ) { $writes++; } return null; };
	add_filter( 'update_post_metadata', $count_fn, 10, 5 ); $GLOBALS['tutorpress_pmpro_lds_reg']['hooks'][] = array( 'update_post_metadata', $count_fn, 10 );
	$req = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions/sort' ); $req->set_param( 'object_id', $same ); $req->set_param( 'ordered_ids', array( $first, $second ) );
	$res = $ctl->sort_subscription_plans( $req );
	tutorpress_pmpro_lds_assert( $res instanceof WP_REST_Response && 200 === (int) $res->get_status() && 0 === $writes, 'unchanged' );
	tutorpress_pmpro_lds_pass( 'persist-unchanged' );
	$false_oid = $base + 5;
	tutorpress_pmpro_lds_assert( $false_oid === (int) wp_insert_post( array( 'import_id' => $false_oid, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'es2f-' . $false_oid ) ), 'false-post' );
	$posts[] = $false_oid;
	update_post_meta( $false_oid, '_tutorpress_pmpro_levels', $preset );
	global $wpdb; $wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $held, 'page_id' => $false_oid ) );
	$block_fn = static function ( $check, $object_id, $meta_key ) { if ( '_tutorpress_pmpro_levels' === $meta_key ) { return false; } return null; };
	add_filter( 'update_post_metadata', $block_fn, 10, 5 ); $GLOBALS['tutorpress_pmpro_lds_reg']['hooks'][] = array( 'update_post_metadata', $block_fn, 10 );
	$req = new WP_REST_Request( 'POST', '/tutorpress/v1/subscriptions/sort' ); $req->set_param( 'object_id', $false_oid ); $req->set_param( 'ordered_ids', $submitted );
	$res = $ctl->sort_subscription_plans( $req ); $stored = array_map( 'intval', (array) get_post_meta( $false_oid, '_tutorpress_pmpro_levels', true ) );
	$page = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $held, $false_oid ) );
	tutorpress_pmpro_lds_assert( $res instanceof WP_Error && 'order_persist_failed' === $res->get_error_code() && 500 === (int) ( $res->get_error_data()['status'] ?? 0 ) && $preset === $stored && 1 === $page, 'false-keep' );
	tutorpress_pmpro_lds_pass( 'persist-false' );
} finally {
	if ( is_int( $sub ) && $sub > 0 ) {
		require_once ABSPATH . 'wp-admin/includes/user.php';
		wp_delete_user( (int) $sub );
	}
	if ( is_int( $author ) && $author > 0 ) {
		require_once ABSPATH . 'wp-admin/includes/user.php';
		wp_delete_user( (int) $author );
	}
	$sort_cleanup();
}
