<?php
require_once __DIR__ . '/bootstrap.php';
require_once dirname( __DIR__, 2 ) . '/includes/utilities/class-pmpro-level-removal-state.php';
require_once dirname( __DIR__, 2 ) . '/includes/utilities/class-pmpro-level-removal-coordinator.php';
require_once dirname( __DIR__, 2 ) . '/includes/utilities/class-pmpro-level-cleanup.php';
$lid = 980000000 + (int) getmypid();
try {
	tutorpress_pmpro_lds_require_local_site();
	$s = '\\TUTORPRESS_PMPRO\\PMPro_Level_Removal_State';
	global $wpdb;
	$p = $lid + 1;
	wp_insert_post( array( 'import_id' => $p, 'post_type' => 'courses', 'post_status' => 'draft', 'post_title' => 'tp1d-' . $p ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $p;
	$pay = array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false );
	$empty = $s::get_object_state( $p );
	tutorpress_pmpro_lds_assert( 'ok' === $empty['result'] && null === $empty['payload'] && array() === $s::get_marked( $p )['level_ids'] && array() === $s::get_blocked_kinds( $p )['blocked_kinds'] && false === $s::get_removed_restriction( $p )['removed_restriction'] && null === $s::get_pair( $p, $lid )['pair'] && 'invalid_state' === $s::get_object_state( 0 )['result'], 'empty' );
	update_post_meta( $p, $s::META_KEY, $pay );
	$s::invalidate_object( $p );
	$ok = $s::get_object_state( $p );
	tutorpress_pmpro_lds_assert( 'ok' === $ok['result'] && $pay === $ok['payload'] && 'retired' === $s::get_pair( $p, $lid )['pair']['state'] && array( $lid ) === $s::get_marked( $p )['level_ids'] && array( 'one_time' ) === $s::get_blocked_kinds( $p )['blocked_kinds'], 'canon' );
	tutorpress_pmpro_lds_assert( $ok === $s::get_object_state( $p ), 'memo' );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( $pay ) ) );
	tutorpress_pmpro_lds_assert( $ok === $s::get_object_state( $p ), 'memo-dup' );
	$s::invalidate_object( $p );
	wp_cache_delete( $p, 'post_meta' );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::get_object_state( $p )['result'], 'dup' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	update_post_meta( $p, $s::META_KEY, $pay );
	$s::invalidate_object( $p );
	$s::get_object_state( $p );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ) );
	$s::invalidate_object( $p );
	$cached = $s::get_object_state( $p );
	tutorpress_pmpro_lds_assert( 'ok' === $cached['result'] && $pay === $cached['payload'], 'meta-cache' );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 2, 'levels' => array(), 'blocked_kinds' => array(), 'removed_restriction' => false ) );
	$s::invalidate_object( $p );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::get_object_state( $p )['result'], 'malformed' );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'unlinked', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	$s::invalidate_object( $p );
	wp_cache_delete( $p, 'post_meta' );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::get_object_state( $p )['result'], 'unlinked-rr' );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'recurring' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	$s::invalidate_object( $p );
	wp_cache_delete( $p, 'post_meta' );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::get_object_state( $p )['result'], 'kind-block' );
	tutorpress_pmpro_lds_pass( 'object reads' );
	$u = $lid + 2; $x = $lid + 3; $r = $lid + 5;
	foreach ( array( $u, $x ) as $id ) { wp_insert_post( array( 'import_id' => $id, 'post_type' => 'courses', 'post_status' => 'draft', 'post_title' => 'tp1d2-' . $id ) ); $GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $id; }
	$lv = function( $id, $ba, $cn ) use ( $wpdb ) { $wpdb->insert( $wpdb->pmpro_membership_levels, array( 'id' => $id, 'name' => 'tp1d2-' . $id, 'description' => '', 'confirmation' => '', 'initial_payment' => 0, 'billing_amount' => $ba, 'cycle_number' => $cn, 'cycle_period' => '', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'allow_signups' => 0 ) ); };
	$lv( $lid, 0, 0 ); $lv( $r, 5, 1 );
	$GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_membership_levels'] = $wpdb->pmpro_membership_levels;
	$wpdb->pmpro_membership_levels = 'tp_lds_missing';
	tutorpress_pmpro_lds_assert( 'unavailable' === $s::classify_live_kind( 0 )['result'] && 'unavailable' === $s::classify_live_kind( -3 )['result'] && 'state_read_error' === $s::classify_live_kind( $lid )['result'], 'kind-id' );
	$wpdb->pmpro_membership_levels = $GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_membership_levels'];
	tutorpress_pmpro_lds_assert( array( 'result' => 'ok', 'kind' => 'one_time' ) === $s::classify_live_kind( $lid ) && array( 'result' => 'ok', 'kind' => 'recurring' ) === $s::classify_live_kind( $r ) && 'unavailable' === $s::classify_live_kind( $lid + 99 )['result'], 'kind' );
	delete_post_meta( $p, $s::META_KEY ); wp_cache_delete( $p, 'post_meta' ); $s::invalidate_object( $p );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $p ) );
	update_post_meta( $p, $s::META_KEY, $pay );
	update_post_meta( $u, $s::META_KEY, array( 'version' => 2, 'levels' => array(), 'blocked_kinds' => array(), 'removed_restriction' => false ) );
	$m = $s::get_level_matches( $lid );
	tutorpress_pmpro_lds_assert( 'ok' === $m['result'] && $pay['levels'][ $lid ] === $m['matches'][ $p ] && ! isset( $m['matches'][ $u ] ) && ! isset( $m['matches'][ $x ] ) && 'invalid_state' === $s::get_level_matches( 0 )['result'], 'level-ok' );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $x ) );
	$m = $s::get_level_matches( $lid );
	tutorpress_pmpro_lds_assert( 'ok' === $m['result'] && ! isset( $m['matches'][ $x ] ), 'level-nostate' );
	$wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'page_id' => $x ) );
	update_post_meta( $x, $s::META_KEY, array( 'version' => 2, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::get_level_matches( $lid )['result'], 'level-expose' );
	delete_post_meta( $x, $s::META_KEY );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( $pay ) ) );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::get_level_matches( $lid )['result'], 'level-dup' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ) );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 2, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::get_level_matches( $lid )['result'], 'level-mal' );
	update_post_meta( $p, $s::META_KEY, $pay );
	$GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_memberships_pages'] = $wpdb->pmpro_memberships_pages;
	$wpdb->pmpro_memberships_pages = 'tp_lds_missing';
	tutorpress_pmpro_lds_assert( 'state_read_error' === $s::get_level_matches( $lid )['result'], 'level-sql' );
	$wpdb->pmpro_memberships_pages = $GLOBALS['tutorpress_pmpro_lds_reg']['wpdb']['pmpro_memberships_pages'];
	tutorpress_pmpro_lds_pass( 'level lookup' );
	delete_post_meta( $p, $s::META_KEY ); delete_post_meta( $u, $s::META_KEY ); wp_cache_delete( $p, 'post_meta' ); wp_cache_delete( $u, 'post_meta' ); $s::invalidate_object( $p ); $s::invalidate_object( $u );
	$wpdb->query( 'START TRANSACTION' );
	$m1 = $s::merge_pair( $p, $lid, 'retired', 'one_time' );
	tutorpress_pmpro_lds_assert( 'ok' === $m1['result'] && (int) $m1['meta_id'] > 0 && array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ) === $m1['payload']['levels'] && array( 'one_time' ) === $m1['payload']['blocked_kinds'] && false === $m1['payload']['removed_restriction'], 'merge-p' );
	$m2 = $s::merge_pair( $p, $r, 'unlinked', 'recurring' );
	tutorpress_pmpro_lds_assert( 'ok' === $m2['result'] && isset( $m2['payload']['levels'][ $lid ], $m2['payload']['levels'][ $r ] ) && 'unlinked' === $m2['payload']['levels'][ $r ]['state'] && array( 'one_time', 'recurring' ) === $m2['payload']['blocked_kinds'] && true === $m2['payload']['removed_restriction'], 'merge-p2' );
	$m3 = $s::merge_pair( $u, $lid, 'retired', 'one_time' );
	tutorpress_pmpro_lds_assert( 'ok' === $m3['result'] && (int) $m3['meta_id'] > 0 && array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ) === $m3['payload']['levels'] && isset( $m2['payload']['levels'][ $r ] ), 'merge-u' );
	$rm = $s::remove_pair( $p, $lid );
	tutorpress_pmpro_lds_assert( 'ok' === $rm['result'] && ! isset( $rm['payload']['levels'][ $lid ] ) && array( 'state' => 'unlinked', 'kind' => 'recurring' ) === $rm['payload']['levels'][ $r ] && array( 'one_time', 'recurring' ) === $rm['payload']['blocked_kinds'] && true === $rm['payload']['removed_restriction'], 'rm-lid' );
	$rm2 = $s::remove_pair( $p, $r );
	tutorpress_pmpro_lds_assert( 'ok' === $rm2['result'] && array() === $rm2['payload']['levels'] && array( 'one_time', 'recurring' ) === $rm2['payload']['blocked_kinds'] && true === $rm2['payload']['removed_restriction'] && (int) $rm2['meta_id'] > 0, 'rm-hist' );
	$cnt = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::merge_pair( 0, $lid, 'retired', 'one_time' )['result'] && 'invalid_state' === $s::merge_pair( $p, 0, 'retired', 'one_time' )['result'] && 'invalid_state' === $s::merge_pair( $p, $lid, 'nope', 'one_time' )['result'] && 'invalid_state' === $s::merge_pair( $p, $lid, 'retired', 'nope' )['result'] && 'invalid_state' === $s::remove_pair( 0, $lid )['result'] && 'invalid_state' === $s::remove_pair( $p, 0 )['result'] && $cnt === (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) && $rm2['payload'] === $s::lock_object_row( $p )['payload'], 'merge-bad' );
	$wpdb->query( 'ROLLBACK' );
	tutorpress_pmpro_lds_assert( '0' === (string) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE post_id IN ( %d, %d ) AND meta_key = %s", $p, $u, $s::META_KEY ) ), 'no-commit' );
	tutorpress_pmpro_lds_pass( 'storage merge' );
	update_post_meta( $p, $s::META_KEY, $pay );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( $pay ) ) );
	wp_cache_delete( $p, 'post_meta' ); $s::invalidate_object( $p );
	$dc = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) );
	tutorpress_pmpro_lds_assert( 2 === $dc && 'invalid_state' === $s::lock_object_row( $p )['result'] && 'invalid_state' === $s::merge_pair( $p, $lid, 'retired', 'one_time' )['result'] && $dc === (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ), 'mut-dup' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ) );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 2, 'levels' => array(), 'blocked_kinds' => array(), 'removed_restriction' => false ) );
	wp_cache_delete( $p, 'post_meta' ); $s::invalidate_object( $p );
	$mal = $wpdb->get_col( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $s::lock_object_row( $p )['result'] && 'invalid_state' === $s::merge_pair( $p, $lid, 'retired', 'one_time' )['result'] && $mal === $wpdb->get_col( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ), 'mut-mal' );
	delete_post_meta( $p, $s::META_KEY ); update_post_meta( $p, $s::META_KEY, $pay ); $s::invalidate_object( $p ); $s::get_object_state( $p );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ) );
	$s::invalidate_object_storage( $p );
	$ns = $s::get_object_state( $p );
	tutorpress_pmpro_lds_assert( 'ok' === $ns['result'] && null === $ns['payload'], 'inv-storage' );
	$gl = 0; $qf = function( $sql ) use ( &$gl ) { if ( false !== stripos( $sql, 'GET_LOCK' ) || false !== stripos( $sql, 'RELEASE_LOCK' ) ) { $gl++; } return $sql; };
	add_filter( 'query', $qf ); $GLOBALS['tutorpress_pmpro_lds_reg']['hooks'][] = array( 'query', $qf );
	tutorpress_pmpro_lds_assert( 'lock_error' === $s::acquire_object_lock( 0 ) && 'lock_error' === $s::acquire_object_lock( -3 ) && 'lock_error' === $s::release_object_lock( 0 ) && 0 === $gl, 'lock-id' );
	remove_filter( 'query', $qf );
	$GLOBALS['tutorpress_pmpro_lds_object_lock'] = '0';
	tutorpress_pmpro_lds_assert( 'busy' === $s::acquire_object_lock( $p ), 'lock-busy' );
	unset( $GLOBALS['tutorpress_pmpro_lds_object_lock'], $GLOBALS['tutorpress_pmpro_lds_object_unlock'] );
	$nm = $s::object_lock_name( $p ); $h = substr( md5( (string) $wpdb->dbname . (string) $wpdb->prefix ), 0, 12 );
	tutorpress_pmpro_lds_assert( 'tp_pmpro_state:' . $h . ':' . $p === $nm && 64 >= strlen( $nm ), 'lock-name' );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $nm;
	tutorpress_pmpro_lds_assert( 'acquired' === $s::acquire_object_lock( $p ) && 'released' === $s::release_object_lock( $p ), 'lock-live' );
	tutorpress_pmpro_lds_pass( 'storage safety' );
	$c = '\\TUTORPRESS_PMPRO\\PMPro_Level_Removal_Coordinator';
	$d = '\\TUTORPRESS_PMPRO\\PMPro_Level_Deletion_Coordinator';
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $lid ), array( '%d' ), array( '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_users, array( 'user_id' => 0, 'membership_id' => $lid, 'status' => 'active', 'code_id' => 0, 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => 'Month', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'startdate' => '2000-01-01 00:00:00' ) );
	$lm = $wpdb->pmpro_membership_levelmeta;
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $lid, 'meta_key' => 'tutorpress_managed', 'meta_value' => '1' ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $lid, 'meta_key' => 'tutorpress_course_id', 'meta_value' => (string) $p ) );
	$sg = "SELECT allow_signups FROM {$wpdb->pmpro_membership_levels} WHERE id = %d";
	$mc = "SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s";
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( $pay ) ) );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( $pay ) ) );
	$s::invalidate_object( $p );
	wp_cache_delete( $p, 'post_meta' );
	tutorpress_pmpro_lds_assert( 'invalid_state' === $c::retire_level( $lid, $p ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && 2 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ), 'rt-dup' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$GLOBALS['tutorpress_pmpro_lds_in_txn'] = true;
	tutorpress_pmpro_lds_assert( 'outer_transaction_active' === $c::retire_level( $lid, $p ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ), 'rt-outer' );
	$GLOBALS['tutorpress_pmpro_lds_in_txn'] = null;
	tutorpress_pmpro_lds_assert( 'transaction_state_unknown' === $c::retire_level( $lid, $p ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ), 'rt-unk' );
	unset( $GLOBALS['tutorpress_pmpro_lds_in_txn'] );
	$GLOBALS['tutorpress_pmpro_lds_lock'] = '0';
	tutorpress_pmpro_lds_assert( 'busy' === $c::retire_level( $lid, $p ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ), 'rt-busy' );
	unset( $GLOBALS['tutorpress_pmpro_lds_lock'] );
	$ln = $d::advisory_lock_name( $lid );
	$on = $s::object_lock_name( $p );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	$GLOBALS['tutorpress_pmpro_lds_txn'] = false;
	tutorpress_pmpro_lds_assert( 'begin_failed' === $c::retire_level( $lid, $p ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rt-begin' );
	unset( $GLOBALS['tutorpress_pmpro_lds_txn'] );
	$row = $wpdb->get_row( $wpdb->prepare( "SELECT id, name, description, confirmation, initial_payment, billing_amount, cycle_number, cycle_period, billing_limit, trial_amount, trial_limit FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ), ARRAY_A );
	$wpdb->delete( $wpdb->pmpro_membership_levels, array( 'id' => $lid ), array( '%d' ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	tutorpress_pmpro_lds_assert( 'unavailable' === $c::retire_level( $lid, $p ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rt-kind' );
	$row['allow_signups'] = 1;
	$wpdb->insert( $wpdb->pmpro_membership_levels, $row );
	tutorpress_pmpro_lds_pass( 'retire_level no-write gates' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	update_post_meta( $p, '_tutorpress_pmpro_levels', array( $lid ) );
	$cf = function( $sql ) use ( $wpdb ) { $q = ltrim( (string) $sql ); if ( 0 === stripos( $q, 'UPDATE' ) && false !== strpos( $q, (string) $wpdb->pmpro_membership_levels ) && false !== strpos( $q, 'allow_signups' ) ) { $GLOBALS['tutorpress_pmpro_lds_txn'] = false; } return $sql; };
	add_filter( 'query', $cf );
	$GLOBALS['tutorpress_pmpro_lds_reg']['hooks'][] = array( 'query', $cf );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	tutorpress_pmpro_lds_assert( 'commit_failed' === $c::retire_level( $lid, $p ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $lid, 'tutorpress_course_id' ) ) && in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rt-cf' );
	remove_filter( 'query', $cf );
	unset( $GLOBALS['tutorpress_pmpro_lds_in_txn'], $GLOBALS['tutorpress_pmpro_lds_lock'], $GLOBALS['tutorpress_pmpro_lds_txn'] );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$s::get_object_state( $p );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	$rt = $c::retire_level( $lid, $p );
	$pl = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $rt && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && is_array( $pl ) && isset( $pl['levels'][ $lid ] ) && 'retired' === $pl['levels'][ $lid ]['state'] && 'one_time' === $pl['levels'][ $lid ]['kind'] && false === $pl['removed_restriction'] && $pl === $s::get_object_state( $p )['payload'] && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $lid, 'tutorpress_course_id' ) ) && in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rt-ok' );
	tutorpress_pmpro_lds_pass( 'retire_level course success' );
	$b = $lid + 4;
	wp_insert_post( array( 'import_id' => $b, 'post_type' => 'course-bundle', 'post_status' => 'draft', 'post_title' => 'tp6d3-' . $b ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $b;
	$gid = $lid + 8;
	$wpdb->insert( $wpdb->pmpro_groups, array( 'id' => $gid, 'name' => 'tp6d3-' . $gid ) );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => '_tutorpress_pmpro_group_id', 'meta_value' => (string) $gid ) );
	$wpdb->insert( $wpdb->pmpro_membership_levels_groups, array( 'level' => $r, 'group' => $gid ) );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $r ), array( '%d' ), array( '%d' ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $r, 'meta_key' => 'tutorpress_managed', 'meta_value' => '1' ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $r, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $b ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $b ) );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => '_tutorpress_pmpro_levels', 'meta_value' => maybe_serialize( array( $r ) ) ) );
	$wpdb->insert( $wpdb->pmpro_memberships_users, array( 'user_id' => 0, 'membership_id' => $r, 'status' => 'active', 'code_id' => 0, 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => 'Month', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'startdate' => '2000-01-01 00:00:00' ) );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	$rn = $d::advisory_lock_name( $r );
	$bn = $s::object_lock_name( $b );
	$inj = function( $sql ) use ( $wpdb, $r, $p ) { if ( ! empty( $GLOBALS['tutorpress_pmpro_lds_injecting'] ) ) { return $sql; } $q = ltrim( (string) $sql ); if ( 0 === stripos( $q, 'START' ) || 0 === stripos( $q, 'COMMIT' ) || 0 === stripos( $q, 'ROLLBACK' ) || 0 === stripos( $q, 'INSERT' ) ) { return $sql; } if ( false !== stripos( $q, 'FOR UPDATE' ) ) { $GLOBALS['tutorpress_pmpro_lds_inject'] = true; return $sql; } if ( ! empty( $GLOBALS['tutorpress_pmpro_lds_inject'] ) && 0 === stripos( $q, 'SELECT' ) && false !== strpos( $q, (string) $wpdb->pmpro_memberships_pages ) ) { $GLOBALS['tutorpress_pmpro_lds_inject'] = false; $GLOBALS['tutorpress_pmpro_lds_injecting'] = true; $wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $p ) ); unset( $GLOBALS['tutorpress_pmpro_lds_injecting'] ); } return $sql; };
	add_filter( 'query', $inj );
	$GLOBALS['tutorpress_pmpro_lds_reg']['hooks'][] = array( 'query', $inj );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $rn;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $bn;
	tutorpress_pmpro_lds_assert( 'shared_unlink' === $c::retire_level( $r, $b ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $r ) ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $b, $s::META_KEY ) ) && (string) $b === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $b ) ) && (string) $b === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $r, 'tutorpress_bundle_id' ) ) && in_array( $r, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, '_tutorpress_pmpro_levels' ) ) ) ), true ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_membership_levels_groups} WHERE `level` = %d AND `group` = %d", $r, $gid ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $r ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $r ) ) && 0 === (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $p ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $rn ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $bn ) ), 'rt-share' );
	remove_filter( 'query', $inj );
	unset( $GLOBALS['tutorpress_pmpro_lds_in_txn'], $GLOBALS['tutorpress_pmpro_lds_lock'], $GLOBALS['tutorpress_pmpro_lds_txn'], $GLOBALS['tutorpress_pmpro_lds_inject'], $GLOBALS['tutorpress_pmpro_lds_injecting'] );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $rn;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $bn;
	$rb = $c::retire_level( $r, $b );
	$plb = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $rb && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $r ) ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $b, $s::META_KEY ) ) && is_array( $plb ) && isset( $plb['levels'][ $r ] ) && 'retired' === $plb['levels'][ $r ]['state'] && 'recurring' === $plb['levels'][ $r ]['kind'] && false === $plb['removed_restriction'] && (string) $b === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $b ) ) && (string) $b === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $r, 'tutorpress_bundle_id' ) ) && in_array( $r, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, '_tutorpress_pmpro_levels' ) ) ) ), true ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_membership_levels_groups} WHERE `level` = %d AND `group` = %d", $r, $gid ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $r ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $r ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $rn ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $bn ) ), 'rt-bun' );
	tutorpress_pmpro_lds_pass( 'retire_level bundle success' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$un = array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'unlinked', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => true );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( $un ) ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$GLOBALS['tutorpress_pmpro_lds_flush_group'] = true;
	tutorpress_pmpro_lds_assert( 'committed_with_warning' === $c::remove_level( $lid, $p ) && $un === maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $lid, 'tutorpress_course_id' ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ), 'rm-retry-warn' );
	unset( $GLOBALS['tutorpress_pmpro_lds_flush_group'] );
	tutorpress_pmpro_lds_assert( 'ok' === $c::remove_level( $lid, $p ) && $un === maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $lid, 'tutorpress_course_id' ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ), 'rm-retry-ok' );
	tutorpress_pmpro_lds_pass( 'remove_level already-unlinked retry' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $lid ), array( '%d' ), array( '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $u ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	$GLOBALS['tutorpress_pmpro_lds_flush_group'] = true;
	$rs = $c::remove_level( $lid, $p );
	$pl = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'committed_with_warning' === $rs && is_array( $pl ) && isset( $pl['levels'][ $lid ] ) && 'unlinked' === $pl['levels'][ $lid ]['state'] && 'one_time' === $pl['levels'][ $lid ]['kind'] && true === $pl['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && ! in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $u === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $u ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rm-share' );
	unset( $GLOBALS['tutorpress_pmpro_lds_flush_group'] );
	tutorpress_pmpro_lds_pass( 'remove_level course shared protected' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $u ), array( '%d', '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $p ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $lid, 'meta_key' => 'tutorpress_course_id', 'meta_value' => (string) $p ) );
	update_post_meta( $p, '_tutorpress_pmpro_levels', array( $lid ) );
	$inj2 = function( $sql ) use ( $wpdb, $lid, $u ) { if ( ! empty( $GLOBALS['tutorpress_pmpro_lds_injecting'] ) ) { return $sql; } $q = ltrim( (string) $sql ); if ( 0 === stripos( $q, 'START' ) || 0 === stripos( $q, 'COMMIT' ) || 0 === stripos( $q, 'ROLLBACK' ) || 0 === stripos( $q, 'INSERT' ) ) { return $sql; } if ( false !== stripos( $q, 'FOR UPDATE' ) ) { $GLOBALS['tutorpress_pmpro_lds_inject'] = true; return $sql; } if ( ! empty( $GLOBALS['tutorpress_pmpro_lds_inject'] ) && 0 === stripos( $q, 'SELECT' ) && false !== strpos( $q, (string) $wpdb->pmpro_memberships_pages ) ) { $GLOBALS['tutorpress_pmpro_lds_inject'] = false; $GLOBALS['tutorpress_pmpro_lds_injecting'] = true; $wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $u ) ); unset( $GLOBALS['tutorpress_pmpro_lds_injecting'] ); } return $sql; };
	add_filter( 'query', $inj2 );
	$GLOBALS['tutorpress_pmpro_lds_reg']['hooks'][] = array( 'query', $inj2 );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	$top = $c::remove_level( $lid, $p );
	$plt = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $top && is_array( $plt ) && isset( $plt['levels'][ $lid ] ) && 'unlinked' === $plt['levels'][ $lid ]['state'] && 'one_time' === $plt['levels'][ $lid ]['kind'] && true === $plt['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && ! in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $u === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $u ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rm-topo' );
	remove_filter( 'query', $inj2 );
	unset( $GLOBALS['tutorpress_pmpro_lds_inject'], $GLOBALS['tutorpress_pmpro_lds_injecting'] );
	tutorpress_pmpro_lds_pass( 'remove_level in-lock topology unlink' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $u ), array( '%d', '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $p ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $lid, 'meta_key' => 'tutorpress_course_id', 'meta_value' => (string) $p ) );
	update_post_meta( $p, '_tutorpress_pmpro_levels', array( $lid ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	$so = $c::remove_level( $lid, $p );
	$pls = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $so && is_array( $pls ) && isset( $pls['levels'][ $lid ] ) && 'retired' === $pls['levels'][ $lid ]['state'] && 'one_time' === $pls['levels'][ $lid ]['kind'] && false === $pls['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $lid, 'tutorpress_course_id' ) ) && in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rm-sole' );
	tutorpress_pmpro_lds_pass( 'remove_level course sole protected' );
	$e = $lid + 7;
	$lv( $e, 0, 0 );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $e ), array( '%d' ), array( '%d' ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $e, 'meta_key' => 'tutorpress_managed', 'meta_value' => '1' ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $e, 'meta_key' => 'tutorpress_course_id', 'meta_value' => (string) $p ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $p ) );
	$wpdb->insert( $wpdb->pmpro_memberships_users, array( 'user_id' => 0, 'membership_id' => $e, 'status' => 'active', 'code_id' => 0, 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => 'Month', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'startdate' => '2000-01-01 00:00:00' ) );
	$en = $d::advisory_lock_name( $e );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $en;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	$GLOBALS['tutorpress_pmpro_lds_object_lock'] = '0';
	$plb = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'busy' === $c::remove_level( $e, $p ) && is_array( $plb ) && isset( $plb['levels'][ $lid ] ) && 'retired' === $plb['levels'][ $lid ]['state'] && ! isset( $plb['levels'][ $e ] ) && $plb === maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $e ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $en ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rm-busy' );
	unset( $GLOBALS['tutorpress_pmpro_lds_object_lock'] );
	tutorpress_pmpro_lds_pass( 'remove_level same-object lock busy' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $r ), array( '%d' ), array( '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $u ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $rn;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $bn;
	$bu = $c::remove_level( $r, $b );
	$plu = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $bu && is_array( $plu ) && isset( $plu['levels'][ $r ] ) && 'unlinked' === $plu['levels'][ $r ]['state'] && 'recurring' === $plu['levels'][ $r ]['kind'] && true === $plu['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $b, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $b ) ) && ! in_array( $r, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $u === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $u ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $r ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $r ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $r ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $rn ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $bn ) ), 'rm-bun-share' );
	tutorpress_pmpro_lds_pass( 'remove_level bundle shared protected' );
	unset( $GLOBALS['tutorpress_pmpro_lds_object_lock'] );
	$wpdb->delete( $wpdb->pmpro_memberships_users, array( 'membership_id' => $e ), array( '%d' ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $en;
	$fd = $c::remove_level( $e, $p );
	$plf = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $fd && is_array( $plf ) && isset( $plf['levels'][ $lid ] ) && 'retired' === $plf['levels'][ $lid ]['state'] && 'one_time' === $plf['levels'][ $lid ]['kind'] && false === $plf['removed_restriction'] && ! isset( $plf['levels'][ $e ] ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $e ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $e, $p ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $e, 'tutorpress_course_id' ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $en ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rm-full' );
	tutorpress_pmpro_lds_pass( 'remove_level course sole unprotected' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	$wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $u ), array( '%d', '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $b ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $r, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $b ) );
	update_post_meta( $b, '_tutorpress_pmpro_levels', array( $r ) );
	$wpdb->insert( $wpdb->pmpro_membership_levels_groups, array( 'level' => $r, 'group' => $gid ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $rn;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $bn;
	$br = $c::remove_level( $r, $b );
	$plr = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $br && is_array( $plr ) && isset( $plr['levels'][ $r ] ) && 'retired' === $plr['levels'][ $r ]['state'] && 'recurring' === $plr['levels'][ $r ]['kind'] && false === $plr['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $b, $s::META_KEY ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $r ) ) && (string) $b === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $b ) ) && (string) $b === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $r, 'tutorpress_bundle_id' ) ) && in_array( $r, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, '_tutorpress_pmpro_levels' ) ) ) ), true ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->pmpro_membership_levels_groups} WHERE `level` = %d AND `group` = %d", $r, $gid ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $r ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $r ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $rn ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $bn ) ), 'rm-bun-sole' );
	tutorpress_pmpro_lds_pass( 'remove_level bundle sole protected' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $lid ), array( '%d' ), array( '%d' ) );
	$wpdb->delete( $wpdb->pmpro_memberships_users, array( 'membership_id' => $lid ), array( '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $u ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $ln;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $on;
	$cu = $c::remove_level( $lid, $p );
	$plc = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $cu && is_array( $plc ) && isset( $plc['levels'][ $lid ] ) && 'unlinked' === $plc['levels'][ $lid ]['state'] && 'one_time' === $plc['levels'][ $lid ]['kind'] && true === $plc['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && ! in_array( $lid, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $u === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $u ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $lid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $ln ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $on ) ), 'rm-share-un' );
	tutorpress_pmpro_lds_pass( 'remove_level course shared unprotected' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	$wpdb->delete( $wpdb->pmpro_memberships_users, array( 'membership_id' => $r ), array( '%d' ) );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $r ), array( '%d' ), array( '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $u ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $rn;
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $bn;
	$bsu = $c::remove_level( $r, $b );
	$pls = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $bsu && is_array( $pls ) && isset( $pls['levels'][ $r ] ) && 'unlinked' === $pls['levels'][ $r ]['state'] && 'recurring' === $pls['levels'][ $r ]['kind'] && true === $pls['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $b, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $b ) ) && ! in_array( $r, array_map( 'intval', (array) maybe_unserialize( $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, '_tutorpress_pmpro_levels' ) ) ) ), true ) && (string) $u === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $u ) ) && (string) $r === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $r ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $r ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT membership_id FROM {$wpdb->pmpro_memberships_users} WHERE membership_id = %d", $r ) ) && (string) $gid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, '_tutorpress_pmpro_group_id' ) ) && (string) $gid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_groups} WHERE id = %d", $gid ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $rn ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $bn ) ), 'rm-bun-share-un' );
	tutorpress_pmpro_lds_pass( 'remove_level bundle shared unprotected' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	$wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $u ), array( '%d', '%d' ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $r, 'page_id' => $b ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $r, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $b ) );
	update_post_meta( $b, '_tutorpress_pmpro_levels', array( $r ) );
	$wpdb->insert( $wpdb->pmpro_membership_levels_groups, array( 'level' => $r, 'group' => $gid ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['locks'][] = $rn;
	$bf = $c::remove_level( $r, $b );
	$plp = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( 'ok' === $bf && is_array( $plp ) && isset( $plp['levels'][ $lid ] ) && 'unlinked' === $plp['levels'][ $lid ]['state'] && 'one_time' === $plp['levels'][ $lid ]['kind'] && true === $plp['removed_restriction'] && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $r ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $r, $b ) ) && null === $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s", $r, 'tutorpress_bundle_id' ) ) && (string) $lid === (string) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) ) && (string) $u === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $u ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $rn ) ) && null === $wpdb->get_var( $wpdb->prepare( 'SELECT IS_USED_LOCK( %s )', $bn ) ), 'rm-bun-full' );
	tutorpress_pmpro_lds_pass( 'remove_level bundle sole unprotected' );
	$ac  = new \TUTORPRESS_PMPRO\Access\Access_Checker();
	$uid = $lid + 6;
	$ckp = 'course_' . $p . '_user_' . $uid . '_access';
	$ckx = 'course_' . $x . '_user_' . $uid . '_access';
	$wpdb->insert( $wpdb->pmpro_memberships_users, array( 'user_id' => $uid, 'membership_id' => $lid, 'status' => 'active', 'code_id' => 0, 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => 'Month', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'startdate' => '2000-01-01 00:00:00' ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['cache'][] = array( 'user_' . $uid . '_levels_active', 'pmpro' );
	$GLOBALS['tutorpress_pmpro_lds_reg']['cache'][] = array( $ckp, 'tutorpress_pmpro' );
	$GLOBALS['tutorpress_pmpro_lds_reg']['cache'][] = array( $ckx, 'tutorpress_pmpro' );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $x ) );
	$s::invalidate_object( $x );
	wp_cache_delete( $x, 'post_meta' );
	get_post_meta( $x, $s::META_KEY, false );
	$ns = 0;
	$qf = function( $sql ) use ( &$ns, $s ) { if ( false !== strpos( (string) $sql, $s::META_KEY ) ) { $ns++; } return $sql; };
	add_filter( 'query', $qf );
	$GLOBALS['tutorpress_pmpro_lds_reg']['hooks'][] = array( 'query', $qf );
	$ax1 = $ac->has_course_access( $x, $uid );
	$n1  = $ns;
	$ax2 = $ac->has_course_access( $x, $uid );
	tutorpress_pmpro_lds_assert( true === $ax1 && true === $ax2 && 0 === $n1 && 0 === $ns, 'ac-unmarked' );
	remove_filter( 'query', $qf );
	wp_cache_set( $ckx, false, 'tutorpress_pmpro', 300 );
	tutorpress_pmpro_lds_assert( true === $ac->has_course_access( $x, $uid ), 'ac-false' );
	wp_cache_set( $ckp, true, 'tutorpress_pmpro', 300 );
	tutorpress_pmpro_lds_assert( true !== $ac->has_course_access( $p, $uid ), 'ac-stale' );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $lid, 'page_id' => $p ) );
	tutorpress_pmpro_lds_assert( true !== $ac->has_course_access( $p, $uid ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && (string) $u === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $u ) ), 'ac-unlink' );
	wp_cache_delete( $ckp, 'tutorpress_pmpro' );
	tutorpress_pmpro_lds_assert( true !== $ac->has_course_access( $p, $uid ), 'ac-cold' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) ) ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$plr = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( true === $ac->has_course_access( $p, $uid ) && is_array( $plr ) && isset( $plr['levels'][ $lid ] ) && 'retired' === $plr['levels'][ $lid ]['state'] && 'one_time' === $plr['levels'][ $lid ]['kind'] && false === $plr['removed_restriction'] && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ), 'ac-retire' );
	tutorpress_pmpro_lds_pass( 'has_course_access unmarked cache and retired holder' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'unlinked', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => true ) ) ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	wp_cache_delete( $ckp, 'tutorpress_pmpro' );
	$lv( $e, 0, 0 );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $p ) );
	$wpdb->insert( $wpdb->pmpro_memberships_users, array( 'user_id' => $uid, 'membership_id' => $e, 'status' => 'active', 'code_id' => 0, 'initial_payment' => 0, 'billing_amount' => 0, 'cycle_number' => 0, 'cycle_period' => 'Month', 'billing_limit' => 0, 'trial_amount' => 0, 'trial_limit' => 0, 'startdate' => '2000-01-01 00:00:00' ) );
	wp_cache_delete( 'user_' . $uid . '_levels_active', 'pmpro' );
	$ai  = $ac->has_course_access( $p, $uid );
	$pli = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( true === $ai && is_array( $pli ) && isset( $pli['levels'][ $lid ] ) && 'unlinked' === $pli['levels'][ $lid ]['state'] && 'one_time' === $pli['levels'][ $lid ]['kind'] && true === $pli['removed_restriction'] && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) ) && (string) $p === (string) $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $e, $p ) ), 'ac-indep' );
	$wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $p ), array( '%d', '%d' ) );
	$wpdb->delete( $wpdb->pmpro_memberships_users, array( 'membership_id' => $e, 'user_id' => $uid ), array( '%d', '%d' ) );
	wp_cache_delete( 'user_' . $uid . '_levels_active', 'pmpro' );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( array( 'version' => 1, 'levels' => array(), 'blocked_kinds' => array(), 'removed_restriction' => false ) ) ) );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( array( 'version' => 1, 'levels' => array(), 'blocked_kinds' => array(), 'removed_restriction' => false ) ) ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	tutorpress_pmpro_lds_assert( false === $ac->has_course_access( $b, $uid ), 'ac-invalid' );
	$enr = wp_insert_post( array( 'post_type' => 'tutor_enrolled', 'post_status' => 'completed', 'post_parent' => $p, 'post_author' => $uid, 'post_title' => 'tp8b2-' . $p ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $enr;
	update_post_meta( $enr, '_tutorpress_pmpro_membership_enrollment', 1 );
	tutorpress_pmpro_lds_assert( true === $ac->should_deny_membership_enrollment( $p, $uid ), 'ac-deny-un' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) ) ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	wp_cache_delete( $ckp, 'tutorpress_pmpro' );
	tutorpress_pmpro_lds_assert( false === $ac->should_deny_membership_enrollment( $p, $uid ) && true === $ac->has_course_access( $p, $uid ), 'ac-deny-rt' );
	tutorpress_pmpro_lds_pass( 'has_course_access independent invalid and stored enrollment' );
	$wpdb->delete( $wpdb->pmpro_memberships_pages, array( 'page_id' => $b ), array( '%d' ) );
	$wpdb->delete( $wpdb->pmpro_membership_levelmeta, array( 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $b ), array( '%s', '%s' ) );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => '_tutorpress_pmpro_levels' ), array( '%d', '%s' ) );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	update_post_meta( $b, '_tutor_course_price_type', 'paid' );
	update_post_meta( $b, 'tutor_course_selling_option', 'one_time' );
	update_post_meta( $b, '_tutorpress_pmpro_levels', array( $lid ) );
	$fe = array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false );
	update_post_meta( $b, $s::META_KEY, $fe );
	$s::invalidate_object( $b );
	do_action( 'rest_api_init' );
	tutorpress_pmpro_lds_assert( false === apply_filters( 'is_course_purchasable', false, $b ), 'fe-marked' );
	update_post_meta( $b, '_tutorpress_pmpro_levels', array( $lid, $e ) );
	tutorpress_pmpro_lds_assert( true === apply_filters( 'is_course_purchasable', false, $b ), 'fe-open' );
	$html = apply_filters( 'tutor/course/single/entry-box/purchasable', '', $b );
	$mk   = (string) $wpdb->get_var( $wpdb->prepare( "SELECT name FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $lid ) );
	$op   = (string) $wpdb->get_var( $wpdb->prepare( "SELECT name FROM {$wpdb->pmpro_membership_levels} WHERE id = %d", $e ) );
	tutorpress_pmpro_lds_assert( '' !== $mk && '' !== $op && false === strpos( $html, $mk ) && false === strpos( $html, '?level=' . $lid ) && false !== strpos( $html, $op ) && false !== strpos( $html, '?level=' . $e ), 'fe-render' );
	tutorpress_pmpro_lds_pass( 'frontend sale filter' );
	update_post_meta( $b, '_tutorpress_pmpro_levels', array( $lid ) );
	$price = apply_filters( 'get_tutor_course_price', 'tp10b-price', $p );
	$page  = $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $p ) );
	tutorpress_pmpro_lds_assert( 'tp10b-price' === $price && (string) $p === (string) $page, 'be-price' );
	$rest = apply_filters( 'tutor_rest_course_single_post', (object) array( 'ID' => $p, 'price' => 'tp10b-price' ) );
	tutorpress_pmpro_lds_assert( is_object( $rest ) && 'tp10b-price' === $rest->price, 'be-rest' );
	$info = apply_filters( 'tutor_course_mini_info', array( 'plans' => array( array( 'id' => $lid ) ) ), get_post( $b ) );
	tutorpress_pmpro_lds_assert( is_array( $info ) && array() === $info['plans'], 'be-plans' );
	tutorpress_pmpro_lds_pass( 'backend sale filter' );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'description' => 'tp10c-marked', 'initial_payment' => 11 ), array( 'id' => $lid ), array( '%s', '%f' ), array( '%d' ) );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'description' => 'tp10c-open', 'initial_payment' => 22 ), array( 'id' => $e ), array( '%s', '%f' ), array( '%d' ) );
	unset( $GLOBALS['pmpro_levels'][ $lid ], $GLOBALS['pmpro_levels'][ $e ] );
	$mp  = number_format_i18n( 11, 2 );
	$opx = number_format_i18n( 22, 2 );
	$has = function( $html, $id, $name, $desc, $amt ) {
		$html = (string) $html;
		return '' !== $name && false !== strpos( $html, $name ) && false !== strpos( $html, $desc ) && false !== strpos( $html, $amt ) && false !== strpos( $html, 'TUTORPRESS_PMPRO_level_radio_' . $id ) && false !== strpos( $html, '?level=' . $id );
	};
	$miss = function( $html, $id, $name, $desc, $amt ) {
		$html = (string) $html;
		return false === strpos( $html, $name ) && false === strpos( $html, $desc ) && false === strpos( $html, $amt ) && false === strpos( $html, 'TUTORPRESS_PMPRO_level_radio_' . $id ) && false === strpos( $html, '?level=' . $id );
	};
	update_post_meta( $b, '_tutorpress_pmpro_levels', array( $lid, $e ) );
	$bh = apply_filters( 'tutor/course/single/entry-box/purchasable', '', $b );
	tutorpress_pmpro_lds_assert( $has( $bh, $e, $op, 'tp10c-open', $opx ) && $miss( $bh, $lid, $mk, 'tp10c-marked', $mp ), 'fe-bundle' );
	$bi = apply_filters( 'tutor_course_mini_info', array( 'plans' => array( array( 'id' => (string) $lid ) ) ), get_post( $b ) );
	$bp = ( isset( $bi['plans'] ) && is_array( $bi['plans'] ) ) ? $bi['plans'] : array();
	tutorpress_pmpro_lds_assert( 1 === count( $bp ) && (string) $e === $bp[0]['id'] && 'tp10c-open' === $bp[0]['description'] && 22.0 === (float) $bp[0]['enrollment_fee'], 'be-bundle' );
	update_post_meta( $p, '_tutor_course_price_type', 'paid' );
	update_post_meta( $p, 'tutor_course_selling_option', 'one_time' );
	update_post_meta( $p, '_tutorpress_pmpro_levels', array( $lid, $e ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $p ) );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'unlinked', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => true ) );
	$s::invalidate_object( $p );
	$ch = apply_filters( 'tutor/course/single/entry-box/purchasable', '', $p );
	tutorpress_pmpro_lds_assert( $has( $ch, $e, $op, 'tp10c-open', $opx ) && $miss( $ch, $lid, $mk, 'tp10c-marked', $mp ), 'fe-course' );
	$ci = apply_filters( 'tutor_course_mini_info', array( 'plans' => array( array( 'id' => (string) $lid ) ) ), get_post( $p ) );
	$cp = ( isset( $ci['plans'] ) && is_array( $ci['plans'] ) ) ? $ci['plans'] : array();
	tutorpress_pmpro_lds_assert( 1 === count( $cp ) && (string) $e === $cp[0]['id'] && 'tp10c-open' === $cp[0]['description'] && 22.0 === (float) $cp[0]['enrollment_fee'], 'be-course' );
	$cr = apply_filters( 'tutor_rest_course_single_post', (object) array( 'ID' => $p, 'price' => 'tp10c-rest' ) );
	tutorpress_pmpro_lds_assert( is_object( $cr ) && 22.0 === (float) $cr->price, 'be-course-price' );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $e, 'page_id' => $b ) );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( $fe ) ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	$ih = apply_filters( 'tutor/course/single/entry-box/purchasable', '', $b );
	tutorpress_pmpro_lds_assert( '' === $ih, 'fe-invalid' );
	$ii = apply_filters( 'tutor_course_mini_info', array( 'plans' => array( array( 'id' => (string) $e, 'description' => 'tp10c-open' ) ) ), get_post( $b ) );
	tutorpress_pmpro_lds_assert( is_array( $ii ) && array() === $ii['plans'], 'be-invalid-plans' );
	$ip = apply_filters( 'get_tutor_course_price', 'tp10c-price', $b );
	tutorpress_pmpro_lds_assert( 'tp10c-price' === $ip, 'be-invalid-price' );
	tutorpress_pmpro_lds_pass( 'sale provider regression' );
	global $wp_filter;
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $b, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $lid ), array( '%d' ), array( '%d' ) );
	unset( $GLOBALS['pmpro_levels'][ $lid ] );
	$admit = false;
	$sale = false;
	$hook = $wp_filter['pmpro_checkout_level'];
	if ( isset( $hook->callbacks[ PHP_INT_MAX ] ) ) {
		foreach ( $hook->callbacks[ PHP_INT_MAX ] as $cb ) {
			$fn = $cb['function'];
			if ( is_array( $fn ) && is_object( $fn[0] ) && $fn[0] instanceof \TUTORPRESS_PMPRO\Pricing\Sale_Price_Handler && 'filter_checkout_level_admission' === $fn[1] ) {
				$admit = true;
			}
		}
	}
	if ( isset( $hook->callbacks[10] ) ) {
		foreach ( $hook->callbacks[10] as $cb ) {
			$fn = $cb['function'];
			if ( is_array( $fn ) && is_object( $fn[0] ) && $fn[0] instanceof \TUTORPRESS_PMPRO\Pricing\Sale_Price_Handler && 'filter_checkout_level_sale_price' === $fn[1] ) {
				$sale = true;
			}
		}
	}
	$bc = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, $s::META_KEY ) );
	$pl = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	tutorpress_pmpro_lds_assert( true === $admit && true === $sale && 0 === $bc && is_array( $pl ) && isset( $pl['levels'][ $lid ] ) && 'retired' === $pl['levels'][ $lid ]['state'] && 'one_time' === $pl['levels'][ $lid ]['kind'] && false === $pl['removed_restriction'] && in_array( 'one_time', $pl['blocked_kinds'], true ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ), 'ck-hook' );
	$normal = pmpro_getLevelAtCheckout( $lid );
	tutorpress_pmpro_lds_assert( null === $normal, 'ck-normal' );
	$disc = pmpro_getLevel( $lid );
	$disc->code_id = 1;
	$disc->discount_code = 'tp11a';
	$dout = apply_filters( 'pmpro_checkout_level', $disc );
	tutorpress_pmpro_lds_assert( null === $dout, 'ck-discount' );
	unset( $GLOBALS['pmpro_levels'][ $lid ] );
	tutorpress_pmpro_lds_pass( 'checkout admission retired' );
	$wpdb->insert( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY, 'meta_value' => maybe_serialize( array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false ) ) ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$inv = pmpro_getLevelAtCheckout( $lid );
	tutorpress_pmpro_lds_assert( null === $inv && 2 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ), 'ck-invalid' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $p, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	update_post_meta( $p, $s::META_KEY, array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'unlinked', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => true ) );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	$plu = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	$up = $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $u ) );
	$open = pmpro_getLevelAtCheckout( $lid );
	tutorpress_pmpro_lds_assert( 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && is_array( $plu ) && isset( $plu['levels'][ $lid ] ) && 'unlinked' === $plu['levels'][ $lid ]['state'] && true === $plu['removed_restriction'] && in_array( 'one_time', $plu['blocked_kinds'], true ) && (string) $u === (string) $up && is_object( $open ) && (int) $open->id === (int) $lid, 'ck-unlinked' );
	$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $x, 'meta_key' => $s::META_KEY ), array( '%d', '%s' ) );
	wp_cache_delete( $x, 'post_meta' );
	$s::invalidate_object( $x );
	update_post_meta( $x, $s::META_KEY, array( 'version' => 2, 'levels' => array(), 'blocked_kinds' => array(), 'removed_restriction' => false ) );
	wp_cache_delete( $x, 'post_meta' );
	$s::invalidate_object( $x );
	$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => 1 ), array( 'id' => $e ), array( '%d' ), array( '%d' ) );
	unset( $GLOBALS['pmpro_levels'][ $e ] );
	$xp = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $x, $s::META_KEY ) ) );
	$xe = $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $e, $x ) );
	$xr = $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$lm} WHERE pmpro_membership_level_id = %d AND meta_key = %s AND meta_value = %s", $e, 'tutorpress_course_id', (string) $x ) );
	$eo = pmpro_getLevelAtCheckout( $e );
	tutorpress_pmpro_lds_assert( 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $x, $s::META_KEY ) ) && is_array( $xp ) && is_array( $xp['levels'] ) && ! array_key_exists( $e, $xp['levels'] ) && 2 === (int) $xp['version'] && null === $xe && null === $xr && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $e ) ) && is_object( $eo ) && (int) $eo->id === (int) $e, 'ck-unrelated' );
	tutorpress_pmpro_lds_pass( 'checkout admission remaining' );
	$retired = array( 'version' => 1, 'levels' => array( $lid => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => false );
	$sign = function( $id, $on ) use ( $wpdb ) {
		$wpdb->update( $wpdb->pmpro_membership_levels, array( 'allow_signups' => $on ), array( 'id' => $id ), array( '%d' ), array( '%d' ) );
		unset( $GLOBALS['pmpro_levels'][ $id ] );
	};
	update_post_meta( $p, $s::META_KEY, $retired );
	wp_cache_delete( $p, 'post_meta' );
	$s::invalidate_object( $p );
	update_post_meta( $p, '_tutorpress_pmpro_levels', array( $lid, $e ) );
	$sign( $lid, 0 );
	$sign( $e, 0 );
	$init = ( new ReflectionClass( '\\TUTORPRESS_PMPRO\\Init' ) )->newInstanceWithoutConstructor();
	$sched = new ReflectionProperty( $init, 'reconcile_scheduled' );
	$sched->setAccessible( true );
	$sched->setValue( $init, array( $p => true ) );
	$course = get_post( $p );
	$init->maybe_reconcile_on_status( 'publish', 'draft', $course );
	$plr = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $p, $s::META_KEY ) ) );
	$pls = get_post_meta( $p, '_tutorpress_pmpro_levels', true );
	tutorpress_pmpro_lds_assert( is_array( $pls ) && in_array( $lid, $pls, true ) && in_array( $e, $pls, true ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $p, $s::META_KEY ) ) && is_array( $plr ) && isset( $plr['levels'][ $lid ] ) && 'retired' === $plr['levels'][ $lid ]['state'] && 'one_time' === $plr['levels'][ $lid ]['kind'] && false === $plr['removed_restriction'] && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $e ) ), 'pub-course' );
	$init->maybe_reconcile_on_status( 'draft', 'publish', $course );
	tutorpress_pmpro_lds_assert( '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $e ) ), 'pub-course-off' );
	update_post_meta( $b, $s::META_KEY, $retired );
	wp_cache_delete( $b, 'post_meta' );
	$s::invalidate_object( $b );
	update_post_meta( $b, '_tutorpress_pmpro_levels', array( $lid, $e ) );
	$sign( $lid, 0 );
	$sign( $e, 0 );
	$sched->setValue( $init, array( $b => true ) );
	$bundle = get_post( $b );
	$init->maybe_reconcile_bundle_on_status( 'publish', 'draft', $bundle );
	$blr = maybe_unserialize( (string) $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $b, $s::META_KEY ) ) );
	$bls = get_post_meta( $b, '_tutorpress_pmpro_levels', true );
	$bp = $wpdb->get_var( $wpdb->prepare( "SELECT page_id FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id = %d AND page_id = %d", $lid, $b ) );
	tutorpress_pmpro_lds_assert( null === $bp && is_array( $bls ) && in_array( $lid, $bls, true ) && in_array( $e, $bls, true ) && 1 === (int) $wpdb->get_var( $wpdb->prepare( $mc, $b, $s::META_KEY ) ) && is_array( $blr ) && isset( $blr['levels'][ $lid ] ) && 'retired' === $blr['levels'][ $lid ]['state'] && 'one_time' === $blr['levels'][ $lid ]['kind'] && false === $blr['removed_restriction'] && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && '1' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $e ) ), 'pub-bundle' );
	$init->maybe_reconcile_bundle_on_status( 'draft', 'publish', $bundle );
	tutorpress_pmpro_lds_assert( '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $lid ) ) && '0' === (string) $wpdb->get_var( $wpdb->prepare( $sg, $e ) ), 'pub-bundle-off' );
	tutorpress_pmpro_lds_pass( 'publish signup gating' );
	$a   = $lid + 9;
	$b   = $lid + 10;
	$sh  = $lid + 11;
	$rt  = $lid + 12;
	$ind = $lid + 13;
	foreach ( array( $a, $b ) as $id ) {
		wp_insert_post( array( 'import_id' => $id, 'post_type' => 'courses', 'post_status' => 'publish', 'post_title' => 'tp13a-' . $id ) );
		$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $id;
	}
	foreach ( array( $sh, $rt, $ind ) as $level_id ) {
		$lv( $level_id, 0, 0 );
	}
	foreach ( array( array( $sh, $a ), array( $sh, $b ), array( $ind, $a ) ) as $pair ) {
		$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $pair[0], 'page_id' => $pair[1] ) );
	}
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $rt, 'meta_key' => 'tutorpress_course_id', 'meta_value' => (string) $a ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $ind, 'meta_key' => 'tutorpress_course_id', 'meta_value' => (string) $b ) );
	update_post_meta( $a, $s::META_KEY, array( 'version' => 1, 'levels' => array( $sh => array( 'state' => 'unlinked', 'kind' => 'one_time' ), $rt => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => true ) );
	wp_cache_delete( $a, 'post_meta' );
	$s::invalidate_object( $a );
	$enroll = ( new ReflectionClass( '\\TUTORPRESS_PMPRO\\Enrollment\\Enrollment_Handler' ) )->newInstanceWithoutConstructor();
	$map    = new ReflectionMethod( $enroll, 'get_courses_for_levels' );
	$map->setAccessible( true );
	$shared  = $map->invoke( $enroll, array( $sh ) );
	$retired = $map->invoke( $enroll, array( $rt ) );
	$indep   = $map->invoke( $enroll, array( $ind ) );
	tutorpress_pmpro_lds_assert( array( $sh => array( $b ), $rt => array(), $ind => array( $a, $b ) ) === array( $sh => $shared['all_courses'], $rt => $retired['all_courses'], $ind => $indep['all_courses'] ), '13a-course-pairs' );
	tutorpress_pmpro_lds_pass( 'course enrollment mapping' );
	$ba  = $lid + 14;
	$bb  = $lid + 15;
	$c1  = $lid + 16;
	$c2  = $lid + 17;
	$bsh = $lid + 18;
	$brt = $lid + 19;
	$bin = $lid + 20;
	tutorpress_pmpro_lds_assert( class_exists( 'TutorPro\\CourseBundle\\Models\\BundleModel' ), '13b-bundle-model' );
	foreach ( array( $ba, $bb ) as $id ) {
		wp_insert_post( array( 'import_id' => $id, 'post_type' => 'course-bundle', 'post_status' => 'publish', 'post_title' => 'tp13b-' . $id ) );
		$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $id;
	}
	foreach ( array( $c1, $c2 ) as $id ) {
		wp_insert_post( array( 'import_id' => $id, 'post_type' => tutor()->course_post_type, 'post_status' => 'publish', 'post_title' => 'tp13b-' . $id ) );
		$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $id;
	}
	foreach ( array( $bsh, $brt, $bin ) as $level_id ) {
		$lv( $level_id, 0, 0 );
	}
	update_post_meta( $ba, 'bundle-course-ids', (string) $c1 );
	update_post_meta( $bb, 'bundle-course-ids', (string) $c2 );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $bsh, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $ba ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $bsh, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $bb ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $brt, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $ba ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $bin, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $ba ) );
	update_post_meta( $ba, $s::META_KEY, array( 'version' => 1, 'levels' => array( $bsh => array( 'state' => 'unlinked', 'kind' => 'one_time' ), $brt => array( 'state' => 'retired', 'kind' => 'one_time' ) ), 'blocked_kinds' => array( 'one_time' ), 'removed_restriction' => true ) );
	wp_cache_delete( $ba, 'post_meta' );
	$s::invalidate_object( $ba );
	$bshared  = $map->invoke( $enroll, array( $bsh ) );
	$bretired = $map->invoke( $enroll, array( $brt ) );
	$bindep   = $map->invoke( $enroll, array( $bin ) );
	tutorpress_pmpro_lds_assert( array( $bsh => array( $c2 ), $brt => array(), $bin => array( $c1 ) ) === array( $bsh => $bshared['all_courses'], $brt => $bretired['all_courses'], $bin => $bindep['all_courses'] ) && array( $bsh => array( $c2 ), $brt => array(), $bin => array( $c1 ) ) === array( $bsh => $bshared['bundle_courses'], $brt => $bretired['bundle_courses'], $bin => $bindep['bundle_courses'] ), '13b-bundle-pairs' );
	tutorpress_pmpro_lds_pass( 'bundle enrollment mapping' );
	$ic  = $lid + 21;
	$lc  = $lid + 22;
	$ilv = $lid + 23;
	$ib  = $lid + 24;
	$lb  = $lid + 25;
	$icd = $lid + 26;
	$lcd = $lid + 27;
	$blv = $lid + 28;
	foreach ( array( $ic, $lc, $icd, $lcd ) as $id ) {
		wp_insert_post( array( 'import_id' => $id, 'post_type' => tutor()->course_post_type, 'post_status' => 'publish', 'post_title' => 'tp13c-' . $id ) );
		$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $id;
	}
	foreach ( array( $ib, $lb ) as $id ) {
		wp_insert_post( array( 'import_id' => $id, 'post_type' => 'course-bundle', 'post_status' => 'publish', 'post_title' => 'tp13c-' . $id ) );
		$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $id;
	}
	foreach ( array( $ilv, $blv ) as $level_id ) {
		$lv( $level_id, 0, 0 );
	}
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $ilv, 'page_id' => $ic ) );
	$wpdb->insert( $wpdb->pmpro_memberships_pages, array( 'membership_id' => $ilv, 'page_id' => $lc ) );
	$bad = array( 'version' => 2, 'levels' => array(), 'blocked_kinds' => array(), 'removed_restriction' => false );
	update_post_meta( $ic, $s::META_KEY, $bad );
	wp_cache_delete( $ic, 'post_meta' );
	$s::invalidate_object( $ic );
	update_post_meta( $ib, 'bundle-course-ids', (string) $icd );
	update_post_meta( $lb, 'bundle-course-ids', (string) $lcd );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $blv, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $ib ) );
	$wpdb->insert( $lm, array( 'pmpro_membership_level_id' => $blv, 'meta_key' => 'tutorpress_bundle_id', 'meta_value' => (string) $lb ) );
	update_post_meta( $ib, $s::META_KEY, $bad );
	wp_cache_delete( $ib, 'post_meta' );
	$s::invalidate_object( $ib );
	$eid = wp_insert_post( array( 'post_type' => 'tutor_enrolled', 'post_status' => 'completed', 'post_parent' => $lc, 'post_title' => 'tp13c-enroll' ) );
	$GLOBALS['tutorpress_pmpro_lds_reg']['posts'][] = $eid;
	update_post_meta( $eid, '_tutor_enrolled_by_order_id', 13 );
	update_post_meta( $eid, '_tutor_pmpro_order_code', 'tp13c' );
	update_post_meta( $eid, '_tutor_pmpro_level_id', $ilv );
	update_post_meta( $eid, '_tutorpress_pmpro_membership_enrollment', 1 );
	update_post_meta( $eid, '_tutorpress_pmpro_membership_level_id', $ilv );
	$stored = function ( $id ) {
		return array(
			'id'     => (int) $id,
			'status' => get_post_status( $id ),
			'parent' => (int) wp_get_post_parent_id( $id ),
			'order'  => get_post_meta( $id, '_tutor_enrolled_by_order_id', true ),
			'code'   => get_post_meta( $id, '_tutor_pmpro_order_code', true ),
			'level'  => get_post_meta( $id, '_tutor_pmpro_level_id', true ),
			'flag'   => get_post_meta( $id, '_tutorpress_pmpro_membership_enrollment', true ),
			'mlvl'   => get_post_meta( $id, '_tutorpress_pmpro_membership_level_id', true ),
		);
	};
	$before = $stored( $eid );
	$cmap   = $map->invoke( $enroll, array( $ilv ) );
	$bmap   = $map->invoke( $enroll, array( $blv ) );
	tutorpress_pmpro_lds_assert( array( $lc ) === $cmap['all_courses'] && array( $lcd ) === $bmap['all_courses'] && array( $lcd ) === $bmap['bundle_courses'], '13c-invalid-pairs' );
	tutorpress_pmpro_lds_assert( $before === $stored( $eid ), '13c-stored-enrollment' );
	tutorpress_pmpro_lds_pass( 'enrollment mapping exclusions' );
} catch ( Throwable $e ) { exit( 1 ); } finally { global $wpdb; if ( '1' === (string) $wpdb->get_var( 'SELECT @@session.in_transaction' ) ) { $wpdb->query( 'ROLLBACK' ); } unset( $GLOBALS['tutorpress_pmpro_lds_in_txn'], $GLOBALS['tutorpress_pmpro_lds_lock'], $GLOBALS['tutorpress_pmpro_lds_object_lock'], $GLOBALS['tutorpress_pmpro_lds_txn'], $GLOBALS['tutorpress_pmpro_lds_flush_group'], $GLOBALS['tutorpress_pmpro_lds_inject'], $GLOBALS['tutorpress_pmpro_lds_injecting'] ); foreach ( $GLOBALS['tutorpress_pmpro_lds_reg']['wpdb'] as $prop => $v ) { $wpdb->$prop = $v; } $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels} WHERE id IN ( %d, %d, %d )", $lid, $lid + 5, $lid + 7 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id IN ( %d, %d, %d )", $lid, $lid + 5, $lid + 7 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->postmeta} WHERE post_id IN ( %d, %d, %d, %d ) AND meta_key = %s", $lid + 1, $lid + 2, $lid + 3, $lid + 4, '_tutorpress_pmpro_level_removal_state' ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->postmeta} WHERE post_id IN ( %d, %d ) AND meta_key = %s", $lid + 1, $lid + 4, '_tutorpress_pmpro_levels' ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = %s", $lid + 4, '_tutorpress_pmpro_group_id' ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_users} WHERE membership_id IN ( %d, %d, %d )", $lid, $lid + 5, $lid + 7 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levelmeta} WHERE pmpro_membership_level_id IN ( %d, %d, %d )", $lid, $lid + 5, $lid + 7 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels_groups} WHERE `group` = %d", $lid + 8 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_groups} WHERE id = %d", $lid + 8 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels} WHERE id IN ( %d, %d, %d )", $lid + 11, $lid + 12, $lid + 13 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id IN ( %d, %d, %d )", $lid + 11, $lid + 12, $lid + 13 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levelmeta} WHERE pmpro_membership_level_id IN ( %d, %d, %d )", $lid + 11, $lid + 12, $lid + 13 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels} WHERE id IN ( %d, %d, %d )", $lid + 18, $lid + 19, $lid + 20 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levelmeta} WHERE pmpro_membership_level_id IN ( %d, %d, %d )", $lid + 18, $lid + 19, $lid + 20 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levels} WHERE id IN ( %d, %d )", $lid + 23, $lid + 28 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_memberships_pages} WHERE membership_id IN ( %d, %d )", $lid + 23, $lid + 28 ) ); $wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->pmpro_membership_levelmeta} WHERE pmpro_membership_level_id IN ( %d, %d )", $lid + 23, $lid + 28 ) ); tutorpress_pmpro_lds_cleanup(); }
